### ISSUE TITLE
Hangups with large files...

### ISSUE THREAD

**Issue by smiffy6969** [AtomLinter/linter-php#10]
Hiya,

thanks for an awesome plugin!

I am having a few issues with larger files, a file with 5396 lines, with the linter turned on, I get really laggy performance on a laptop mor ethan capable (plenty of RAM and SSD).... The system is installed on linux (ubuntu-gnome).

I get hangs of around 1 to 2 seconds per keypress before the UI updates, this is random, comes and goes but is not connected with anything else happening at the same time. 

Turning the linter off helps a lot... I understand that linters do impact performance, just wondering what your file size limits are like before you start to see issues.

regards

Paul

**Comment by hd-deman** [comment]
Just enable `lint on save` and disable `lint on change`. see how https://github.com/AtomLinter/linter-php/issues/8

**Comment by steelbrain** [comment]
Fixed by the latest Linter version.
