### ISSUE TITLE
Error after updating to 1.1.4

### ISSUE THREAD

**Issue by alexbet** [AtomLinter/linter-php#105]
After updating to v1.1.4, I am getting the following error while typing:

```
Error: Column start (8) greater than line length (4) at Object.module.exports.Helpers.rangeFromLineNumber (/Users/UserName/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers/coffee:73:73)
 at /Users/UserName/.atom/packages/linter-php/lib/main.coffee:58:30

```

**Comment by alexbet** [comment]
BTW, if it helps, I notice that I am getting this error while I am writing code within if..else and foreach statements.

**Comment by Arcanemagus** [comment]
_Just_ fixed this in v1.1.5, please update and test :wink:.

**Comment by alexbet** [comment]
It seems to be OK now. Thanks! :)

**Comment by alexbet** [comment]
Spoke too soon. Now I am getting this: :(

```
Error; Column start (11) greater than line length (5) at Object.module.exports.Helpers.rangeFromLineNumber (/Users/UserName/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.coffee:158:15)
at /Users/UserName/.atom/packages/linter-php/lib/main.coffee:58:30
at process._tickCallback (node.js: 368:9)
```

**Comment by Arcanemagus** [comment]
Do you have a file to test this with? That should have fixed this for the only case we have been able to reproduce so far.

**Comment by alexbet** [comment]
It doesn't do it very often, so let me see when it does it, and I will send you the file and tell you what to do to recreate it. Stay tuned.

**Comment by Arcanemagus** [comment]
Just was able to reproduce in a sideways manner, Atom is being liberal with the "compatible with version" and loading an older version from a different package. Will verify with a known up to date version.

**Comment by alexbet** [comment]
OK, great! Just FYI, I have the latest Atom 1.2.3 installed.

**Comment by alexbet** [comment]
Here is what does it for me. Look at this code...
```
if ($rows) {
	$i = 0;
	foreach ($rows as $row)	{
		$variable....
	}
}
```
As soon as I start typing "$variable" with in foreach, it shows the error with every key stroke. Hope this helps.

**Comment by Arcanemagus** [comment]
Do you have a raw file to test this with (uploaded in a gist)? It looks like you should be on the current version, assuming the update worked, but that error shouldn't be triggering for you.

Every time you save this error should trigger on a file that you see that on.

**Comment by alexbet** [comment]
I saw that you had a new update. I installed it and the error hasn't happened since this latest update. Thanks!

**Comment by Arcanemagus** [comment]
That update would only have made it stop cutting off the last character of the range, so if it had any effect it simply worked around Atom's bug with loading older libraries than the packages have requested.

In any case since it definitely sounds like it's an issue with that library getting updated I'm going to mark this as closed.
