### ISSUE TITLE
[Feature Request] Support Laravel Blade

### ISSUE THREAD

**Issue by Stanzilla** [AtomLinter/linter-php#108]
Is it feasible to include Laravel Blade support in the php linter or would that be better off in a own project?

**Comment by Arcanemagus** [comment]
Are Laravel Blade templates valid for _plain_ PHP? This linter simply runs `php -l` on the files...

**Comment by Stanzilla** [comment]
Nope but you can use vanilla php inside .blade files

**Comment by Arcanemagus** [comment]
That would be better off for its own project then as you would have to implement (or use) some parser to split out the PHP code from the rest of the file before passing it on to `php -l`.

Feel free to clone this and plug in whatever you need to get a working version for what you are intending, and if you have any problems as in #linter on Atom's Slack instance and we will do what we can to help.
