### ISSUE TITLE
Problem with using it on Windows

### ISSUE THREAD

**Issue by Sogl** [AtomLinter/linter-php#109]
Hi!

I tried to use this package and it doesn't work. 
What I did:
1. Install `linter` and `linter-php` packages.
2. Put `C:\OpenServer\modules\php\PHP-5.5` to PHP Executable Path, also tried with other slashes `C:/OpenServer/modules/php/PHP-5.5`. My PHP module is portable as part of portable WAMP OpenServer.
3. Linter not working:
![image](https://cloud.githubusercontent.com/assets/7556290/11492723/b57c260a-983c-11e5-9b49-0c59a69ce8ea.png)
As you can see, I missed `$` near variable.

What I'm doing wrong?

**Comment by Arcanemagus** [comment]
Nothing, that's not a syntax error :wink:.

This linter only runs the equivalent of `php -l` on the file, which is _only_ a syntax check, not a semantic check. You probably want to also install `linter-phpmd` and `linter-phpcs` if you want more advanced semantic checking.

**Comment by Arcanemagus** [comment]
Well, to be clear that particular example you gave shouldn't have an error, you may want to verify you are getting something with an invalid file:
![image](https://cloud.githubusercontent.com/assets/427137/11493078/a590b1ea-97a9-11e5-9716-e104073665a2.png)

**Comment by Sogl** [comment]
I saw message `Unable to determine php version`... 
The message disappears very quickly. Where I can watch it again?

**Comment by Sogl** [comment]
Something strange:
![image](https://cloud.githubusercontent.com/assets/7556290/11493199/9edd6fee-9841-11e5-91df-357e12cf7ac5.png)

**Comment by Arcanemagus** [comment]
At this point I'm not entirely sure, I would imagine it's something wrong with your custom PHP installation. Is [open-server.ru](http://open-server.ru/) what you have installed?

The error messages look like bad encoding translation, which would make sense for that being the source of the install.

**Comment by Sogl** [comment]
>Is open-server.ru what you have installed?
Yep

Do I need to add `php.exe` to my path?

**Comment by Arcanemagus** [comment]
What you put in the Executable Path setting should be the full path to `php`, for example on my system it would be:
`C:\php5\php.exe`

In your case I would guess that it would be:
`C:\OpenServer\modules\php\PHP-5.5\php.exe`

But I'm just guessing as to the full path there.

**Comment by Sogl** [comment]
Hmm... With full path:
![image](https://cloud.githubusercontent.com/assets/7556290/11493619/3be5c4b8-9846-11e5-8f22-d647e1acbb9f.png)

I think I need to install php from installer in my system

**Comment by Arcanemagus** [comment]
Did that get things working for you? Btw the error message might mean it couldn't find the file, I can't read Russian though so I'm just guessing :stuck_out_tongue:.

**Comment by Sogl** [comment]
Something strange... now I can't see edit path in package settings =(

**Comment by Arcanemagus** [comment]
Can you open Developer Tools, put a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.1.6/lib/main.coffee#L52) and see what the output of the command is? (You may want to put one before the execute just to see if it's working.)

**Comment by Sogl** [comment]
I need to open `main.coffee` file in a new tab and put break to this line? 
And how to show DevTools? `Ctrl + Shift + I` and `F12` not working...
Sorry, I have never worked with Atom debugger.

**Comment by Arcanemagus** [comment]
View -> Developer -> Toggle Developer Tools

Find the file in the sources tab and put a breakpoint on the line I linked to (the line number _might_ be different but the contents should be the same).

**Comment by imuhammadshoaib** [comment]
Resolved for PHP:
Just go to  your `~/.atom/config.cson` file.
```
'linter-php':
  # php path. run 'which php' to find the path 
   executablePath: "C:\\wamp\\bin\\php\\php5.5.12\\php"
```

**Comment by Arcanemagus** [comment]
@imuhammadshoaib That shouldn't be necessary if `php` is in your PATH, but if it isn't that is how you would work around it... as stated in the README.

I'm marking this as closed due to a lack of response, @Sogl if you are still having issues please feel free to re-open this :wink:.

**Comment by faysalme** [comment]
![cavbvbpture](https://cloud.githubusercontent.com/assets/16570216/21260359/b375c9ac-c3af-11e6-8aef-6a38a14f7b35.JPG)

i select the path form the xampp/php folder

**Comment by Arcanemagus** [comment]
@faysalah Please file a new issue, from what you posted though it seems you have typed "lin" into the Executable Path setting, and it obviously can't find that.
