### ISSUE TITLE
linter-php > 1.1.0 doesn't work, 1.1.0 works OK

### ISSUE THREAD

**Issue by ricpelo** [AtomLinter/linter-php#113]
Using Atom 1.3.1.

When I open atom with PHP files already opened, linter-php 1.1.0 works OK, but 1.1.1 doesn't (shows 'No issues' but the PHP file has syntax errors).

**Comment by ulrik59** [comment]
I have the same problem using Atom 1.3.1, linter 1.11.3 and linter-php 1.16. PHP Executable path is set.

**Comment by Arcanemagus** [comment]
This is actually an Atom bug, it is fixed in the v1.4.0 betas if you want to switch to there and try it out, otherwise for now you just need to open a PHP file (or close and re-open one) for Atom to properly activate this package.

**Comment by ricpelo** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
No problem, can't wait for v1.4.0 to release to stable so I can move the other linters to this activation method. It will speed up Atom's launching when you have many of them installed at once but I've been holding off due to this bug :frowning:.
