### ISSUE TITLE
linter-php is not activated on initial Atom session load

### ISSUE THREAD

**Issue by ginevive** [AtomLinter/linter-php#114]
**Environment**
Atom v1.3.2
linter v1.11.3
linter-php v1.1.6

**Issue Explanation**
After opening Atom with files left open from the last session linter-php will not display any error messages.  The status bar states "No Issues" for all files.  This applies to existing errors and newly created errors.  Refreshing does not resolve the issue. 

The only way I have been able to get linter-php to activate on those pages is to close and reopen each file.  

**Side Note**
I have two more linter plugins installed, linter-csslint and linter-jshint.  Neither of these plugins have this issue.

**Comment by Arcanemagus** [comment]
This is an Atom bug with `activationHooks`. It is fixed in the v1.4.0 betas if you want to switch to those. If not you can work around the bug by either opening a different PHP file, or closing and re-opening the one you are currently editing.
