### ISSUE TITLE
Error: PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/imap.so' 

### ISSUE THREAD

**Issue by AceoK** [AtomLinter/linter-php#116]
Every time when I change something in file

**Comment by Arcanemagus** [comment]
Sounds like you have an issue with your PHP configuration file (Invalid path to the IMAP module?).

Do you get the same error when running PHP from the command line?

**Comment by AceoK** [comment]
I have php7 on my Arch, and all configurations is from arch wiki

**Comment by Arcanemagus** [comment]
This package simply runs `php -l` on the file you are currently editing and reports back the error, so do you see the same error when running `php -l foo.php`?

**Comment by Arcanemagus** [comment]
Just a note, looks like this needs a bit of modification to work with PHP7, so once you get this error figured out it unfortunately won't show errors. I'll try to get that fixed later today.

**Comment by Arcanemagus** [comment]
@AceoK have you tried running php from the terminal yet?

**Comment by AceoK** [comment]
@Arcanemagus yes, You are right, it's not plugin error. Sorry for that

**Comment by Arcanemagus** [comment]
Not a problem :wink:

Marking this as closed since this isn't an issue with linter-php, feel free to keep posting if you need any help though.
