### ISSUE TITLE
Failed to spawn command php. Make sure php is installed and on your PATH

### ISSUE THREAD

**Issue by fnkr** [AtomLinter/linter-php#127]
#86 is happening again.

![image](https://cloud.githubusercontent.com/assets/616991/12866297/0a51657a-ccca-11e5-9b5f-1d9a0514c8d8.png)

Related commit: https://github.com/AtomLinter/linter-php/commit/18af495258cb89d550f7601974633f67b4a6cc1e

**Comment by Arcanemagus** [comment]
I'm actually just going to re-open #86.

**Comment by fnkr** [comment]
Seems legit, thanks!
