### ISSUE TITLE
Error: Invalid TextEditor provided

### ISSUE THREAD

**Issue by ihsw** [AtomLinter/linter-php#128]
Hi I am getting this error.

    Error: Invalid TextEditor provided
      at _validateEditor (/home/adrian/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:143:11)
      at Object.rangeFromLineNumber (/home/adrian/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:164:3)
      at /home/adrian/.atom/packages/linter-php/lib/main.coffee:58:30

**Comment by absalan** [comment]
I have same issue on windows 10.

Error: Invalid TextEditor provided
    at _validateEditor (C:\Users\pc\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.js:143:11)
    at Object.rangeFromLineNumber (C:\Users\pc\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.js:164:3)
    at file:///C:/Users/pc/.atom/packages/linter-php/lib/main.coffee:58:30
    at process._tickCallback (node.js:368:9)

**Comment by Arcanemagus** [comment]
Do you get the error all the time, or was it a one off thing? Are you on the latest version of Atom, `linter`, and `linter-php`?

**Comment by Arcanemagus** [comment]
If you are on the latest versions, do you have any steps to reproduce?

**Comment by matheusb96** [comment]
same here, any function that i type in atom an alert is displayed... i guess when i'm writting and atom show options to autocomplete the error message pops up

**Comment by pleaseshutup** [comment]
I was getting this error on a version of atom earlier than the current 1.5 (which was 1.3.x i think) and updating to the latest version works fine and I no longer receive these errors.

**Comment by Arcanemagus** [comment]
Ah ha! I bet you this is relating to https://github.com/AtomLinter/atom-linter/issues/107 :frowning:

**Comment by ihsw** [comment]
After upgrading to atom-1.5 the error is gone.

**Comment by Arcanemagus** [comment]
Good to know, thanks for reporting back @ihsw. I'm going to mark this as closed since the root issue seems to be the atom-linter issue linked above, thanks for the reports!

**Comment by matheusb96** [comment]
i updated my atom to 1.5 and now it's running perfect, thanks guys
