### ISSUE TITLE
Linter throws exception on saving any PHP file

### ISSUE THREAD

**Issue by rickgregory** [AtomLinter/linter-php#131]
This is with 1.18 and the latest Atom on Mac OS 10.11.3. On saving any .php file I get the error in the attached text file. The PHP file isn't parsed (a file with a known error shows as "No Issues" in Atom.
[phplinterr.txt](https://github.com/AtomLinter/linter-php/files/128516/phplinterr.txt)

This has worked fine in the past (it broke on the latest update) and yes, php is on my path.

**Comment by Arcanemagus** [comment]
Looks like this might be a bug in the `consistent-path` dependency of the `atom-linter` dependency, can you run `npm list` in `~/.atom/packages/linter-php`?

**Comment by rickgregory** [comment]
Here you go: 

path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:327:31)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:435:26)

**Comment by Arcanemagus** [comment]
Thanks! Will have to see what @steelbrain says as it's his package (or I might have time later to dive into it and try to figure out what is going on...).

**Comment by rickgregory** [comment]
Hit me up if you need more info. As another point of info, the phpmd linter fails with a similar (perhaps the same) error.

**Comment by Arcanemagus** [comment]
If the bug lays where I think it does almost all linters will be hit by it unfortunately, since that is the package we use to workaround OSX's empty environment.

**Comment by rickgregory** [comment]
Yep. Turned on the SCSS linter and... same thing.

**Comment by steelbrain** [comment]
@rickgregory If I had to guess, your atom is inheriting a very screwed up `$PATH` and doesn't have even the basic commands in it, while I have opened this issue in the appropriate repo, can you provide us the value of `process.env.PATH` from your Atom? (open dev tools and write this, you'll get the value)

**Comment by rickgregory** [comment]
process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"

is what I get.

**Comment by steelbrain** [comment]
This is what I get on vanilla ubuntu
```
/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by rickgregory** [comment]
Bingo. I updated the path to read /usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

(there's some duplication there) and we're good. Unsure of how PATH got mangled. Thanks.

**Comment by rickgregory** [comment]
OK, so I updated linter and ... back to the old, bad path.

**Comment by Arcanemagus** [comment]
Marking this as closed, there have been _many_ updates since this issue was last updated, if you are still having problems please file a new issue.
