### ISSUE TITLE
Line length

### ISSUE THREAD

**Issue by Torniojaws** [AtomLinter/linter-php#150]
It would be great to have a setting for desired line length. Atom itself of course has one, but if you want to keep different line lengths for different languages, eg. 80 chars for Python and 120 chars for PHP, it would be easier to configure it in the linter for each language.

**Comment by Arcanemagus** [comment]
This linter is only the equivalent of running `php -l` on the code, which _only_ checks for syntax issues. If you want a semantic check (such as line length) you should look into running `linter-phpcs` and/or `linter-phpmd`.

There is nothing wrong with running all three at once :wink:.
