### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by user58258** [AtomLinter/linter-php#152]
I'm running atom v1.7.0-beta1 from

    https://github.com/atom/atom/releases/tag/v1.7.0-beta1

When I open atom I get an error

    Uncaught Error: spawn EACCES0
    /usr/share/atom-beta/resources/app.asar/src/buffered-process.js:262
    Hide Stack Trace
    Error: spawn EACCES
        at exports._errnoException (util.js:856:11)
        at ChildProcess.spawn (internal/child_process.js:298:11)
        at Object.exports.spawn (child_process.js:374:9)
        at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:190:44)
        at new BufferedProcess (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:52:14)
        at /home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:58:77
        at Object.<anonymous> (/home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:23:18)
        at [object Generator].next (native)
        at step (/home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:191)
        at /home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:368

and it says

    The error was thrown from the linter-php package. This issue has already been reported.

and points to this issue

    Uncaught Error: spawn EACCES #62
    https://github.com/AtomLinter/linter-php/issues/62

That's been closed, and I don't see how to reopen it.

So I created this new.

Fyi, in my config.cson I already have

    "*":
      core:
      ...
      "linter-php":
        executablePath: "/usr/local/php7/bin/php"

And

    which php
        /usr/local/php7/bin/php
    php -v | head -n 1
        PHP 7.0.6-dev (cli) (built: Mar 17 2016 11:30:22) ( NTS )

**Comment by Arcanemagus** [comment]
Is Atom running as a different user than your terminal session?

Issue #62 was because that person had put a _directory_ in as the path the the `php` _binary_. What does the settings screen within Atom show for that setting?

**Comment by user58258** [comment]
> Is Atom running as a different user than your terminal session?

no

> What does the settings screen within Atom show for that setting?

Atom's main settings screen doesn't have anything about the bin.

In the linter-php package's settings

    Settings
        PHP Executable Path
            /usr/local/php7/bin/php

**Comment by Arcanemagus** [comment]
What does `ls -l php` show in the `/usr/local/php7/bin` folder? Something is wrong with permissions _somewhere_ that is preventing this from running.

**Comment by user58258** [comment]
> What does ls -l php show in the /usr/local/php7/bin folder? Something is wrong with permissions somewhere that is preventing this from running.

    cd /usr/local/php7/bin
    ls -l php
        -rwxr-xr-x+ 1 root root 4.4M Mar 17 12:05 php*
    whoami
        dev
    /usr/local/php7/bin/php -v
        PHP 7.0.6-dev (cli) (built: Mar 17 2016 11:30:22) ( NTS )
        Copyright (c) 1997-2016 The PHP Group
        Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
            with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by user58258** [comment]
> Issue #62 was because that person had put a directory in as the path the the php binary
This appears then to be a different bug.  But the error dialog in Atom still is pointing to #62 as "Already Filed" ...

**Comment by user58258** [comment]
issue persists in atom 1.8b

    atom-beta --version
        Atom    : 1.8.0-beta3
        Electron: 0.36.8
        Chrome  : 47.0.2526.110
        Node    : 5.1.1

    Uncaught Error: spawn EACCES
    /usr/share/atom-beta/resources/app.asar/src/buffered-process.js:262
    Hide Stack Trace
    Error: spawn EACCES
        at exports._errnoException (util.js:856:11)
        at ChildProcess.spawn (internal/child_process.js:298:11)
        at Object.exports.spawn (child_process.js:374:9)
        at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:190:44)
        at new BufferedProcess (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:52:14)
        at /home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:58:77
        at Object.<anonymous> (/home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:23:18)
        at [object Generator].next (native)
        at step (/home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:191)
        at /home/dev/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:114:368

**Comment by Arcanemagus** [comment]
Can you go into the `linter-php` package folder and run `npm install atom-linter@~4.6.0`?

**Comment by user58258** [comment]
exec

    cd ~/.atom/packages/linter-php
    npm install atom-linter@~4.6.0
        - sb-promisify@1.1.1 node_modules/atom-linter/node_modules/sb-promisify
        consistent-env@1.1.2 node_modules/atom-linter/node_modules/consistent-env -> node_modules/consistent-env
        named-js-regexp@1.3.1 node_modules/atom-linter/node_modules/named-js-regexp -> node_modules/named-js-regexp
        os-tmpdir@1.0.1 node_modules/atom-linter/node_modules/tmp/node_modules/os-tmpdir -> node_modules/os-tmpdir
        tmp@0.0.28 node_modules/atom-linter/node_modules/tmp -> node_modules/tmp
        linter-php@1.2.0 /home/test/.atom/packages/linter-php
        └─┬ atom-linter@4.6.1
          └── sb-promisify@1.3.0 


open atom v1.8.0-beta3.

no more error reported.  so a workaround that works.

what needs to change in the package or app install so that the workaround-step isn't needed?

**Comment by Arcanemagus** [comment]
@steelbrain looks like it wasn't _just_ that one package's specs that are affected by that change in v4.7.0, what steps need to be done to test this further?

**Comment by steelbrain** [comment]
@Arcanemagus We can fix the specs in packages by updating `atom-linter` from
```js
export { exec, execNode } from 'sb-exec'
```
to
```js
import { exec, execNode } from 'sb-exec'
export { exec, execNode }
```

**Comment by Arcanemagus** [comment]
Closing as this was an external issue.
