### ISSUE TITLE
linter-php: Unable to determine PHP version

### ISSUE THREAD

**Issue by jkw** [AtomLinter/linter-php#153]
php 7.0.5 is located at f:\php
I point to f:\php\php.exe still says it can't find out version?

**Comment by Arcanemagus** [comment]
What is the _exact_ output of running `php -v`?

**Comment by marcelomendes** [comment]
Same here (Debian Unstable):

php -v

PHP 7.0.5-2+b1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by millipedia** [comment]
Ditto on OSX 10.11.4. I get a warning about not being able to determine PHP, but then the linter runs fine with no errors. It also isn't consistent (love that in a bug) - mostly firing when I launch atom the first time or add a new project folder so maybe you're just not getting a response in time?

php -v 

PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by Arcanemagus** [comment]
If you put the output of `which php` into the Executable Path setting does the error get fixed?

**Comment by millipedia** [comment]
> which php
/usr/bin/php

'Unable to determine the version of "/usr/bin/php", please verify that this is the right path to PHP' 

Again - this only happens occasionally. It happened on first firing up Atom this morning and once yesterday but most of the time there's no error and the linter always works (so frankly I'm not too upset by this bug).

**Comment by Grigory90** [comment]
I am using the latest build of **PHP 7.0.6**, there is no problem.

**Comment by dryaner** [comment]
I'm having the same problem with the next configuration.
wamp.
php 5.6.19
atom 1.9.8

PHP 5.6.19 (cli) (built: Mar  2 2016 20:09:42)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by IvanNieto** [comment]
My prompt on php -v was 

> PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
> PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
> with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

Solved it just deleting a duplicated call to load mcrypt module in my php.ini (/etc/php/7.0/cli/php.ini). Maybe could be helpful for other users, check for problems on php.ini configuration. 

Anyway, had you stated the complete path to php in the linter-php settings in Atom? Not sure about that, but don't leave it as default so you're securing it reaches the absolute path.

**Comment by massimilianomancini** [comment]
Same here with windows 10 x64 and PHP 7.0.11, Atom 1.10.2.

Here is the php -v output

`PHP 7.0.11 (cli) (built: Sep 13 2016 15:37:04) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans`

**Comment by shylor** [comment]
Windows 10 x64

`PHP 7.0.10 (cli) (built: Aug 18 2016 09:48:53) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies`

**Comment by giannisp** [comment]
Same error today after upgrading to `1.3.0`.

```
$ php -v
PHP 7.0.11 (cli) (built: Oct  3 2016 08:53:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by benweier** [comment]
I'm experiencing this issue now.

macOS Sierra
Atom 1.11.1
linter-php 1.3.0

```
$ which php
/usr/local/opt/php56/bin/php
```

```
$ php -v
PHP 5.6.19 (cli) (built: Mar 14 2016 11:55:51)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by giannisp** [comment]
Here is a quick fix for this: https://github.com/AtomLinter/linter-php/pull/215/files

**Comment by Arcanemagus** [comment]
v1.3.0 introduced a bug that was fixed in v1.3.1, but didn't relate to the previous reports.

**Comment by benweier** [comment]
Confirming #215 has fixed the issue in `1.3.1`. Thanks!

**Comment by RustyAxeGames** [comment]
I'm getting a "unable to determine the version of PHP"

Here's the config entry I added and which I've tried a couple dozen variants of.

  "linter-php":
    executablePath: "c:\\xampp\\php"

**Comment by Arcanemagus** [comment]
@jkw, @marcelomendes, @millipedia, @dryaner, @massicode, @shylor:

Are any of you still seeing this on v1.3.1?

**Comment by millipedia** [comment]
All seems to be working fine for me in 1.3.1
I've not actually seen the error for a while now so really not sure what fixed it but I'm happy to close this bug.

**Comment by shylor** [comment]
It seems to be working with me now as well. Yay!

**Comment by Arcanemagus** [comment]
Marking this as closed, if anyone is still experiencing this please file a new issue!
