### ISSUE TITLE
Linter marks getting value from array returned from function as incorrect.

### ISSUE THREAD

**Issue by AfroSpartan** [AtomLinter/linter-php#157]
The package does not seem to like `$Order->get_details()["orderItems"]` even though the code runs fine and php doesn't have any problems with it.

**Comment by Arcanemagus** [comment]
What do you get when you run `php -l` on that file?

**Comment by AfroSpartan** [comment]
Just 1 notice about $Order not being set. It is always set by the time this is called though.

**Comment by Arcanemagus** [comment]
Is this plugin reporting anything _different_ from what running `php -l` on the file shows?

**Comment by AfroSpartan** [comment]
Yes it's saying that is causing a parse error but php is fine with it and only comes up with notices.
The plugin is fine with `$Order->get_details()` but not `$Order->get_details()["orderItems"]`.

**Comment by Arcanemagus** [comment]
What OS are you on?

**Comment by AfroSpartan** [comment]
I am on OS X 10.8.5
Atom is using PHP 5.3.29 but the server is using 5.5.21. I ran php -l on the file with 7.0.0 and just now with 5.3.29 both of which only came up with the one notice, no parse errors.

**Comment by Arcanemagus** [comment]
If you place a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/lib/main.coffee#L52) what does `output` contain?

**Comment by AfroSpartan** [comment]
output: "Parse error: parse error in - on line 124↵Errors parsing -"

**Comment by Arcanemagus** [comment]
This is just _bizarre_, and the version shown when you did the breakpoint from [this comment](https://github.com/AtomLinter/linter-php/issues/157#issuecomment-214798457) was the same 5.3.29 you tried manually?

**Comment by AfroSpartan** [comment]
The one I tried manually is from MAMP since I was having trouble getting the one installed on this machine to work through the terminal.
I just tried it with the installed version (the one atom is using) and it's coming up with that parse error, which is strange since they're both the same version.

**Comment by Arcanemagus** [comment]
I would recommend overriding the executable path in the settings to force using the version of `php` that you would like to use, which should get rid of that error.

**Comment by AfroSpartan** [comment]
I updated PHP to 5.6.21 and it seems fine now
