### ISSUE TITLE
No linter message

### ISSUE THREAD

**Issue by yinanfang** [AtomLinter/linter-php#163]
I've installed the linter-php and set up the executable path. However, there's no error message showing up. One of the reason I can think of is that I'm using nuclide. The nuclide-diagnostics asked me to disable the  linter package and so I did. The linter-eslint is still working fine as its output appears int he nuclide debugger. However, linter-php is not showing anything. Do you think this is a nuclide problem or linter-php problem. Is there any way to make these two work together?

**Comment by Arcanemagus** [comment]
If `linter-eslint` is working, then `linter-php` _should_ be working as well.

If you run `Editor: Log Cursor Scope` from the command palette what scopes are listed?

**Comment by yinanfang** [comment]
I tried a couple places in that php file. Here's a screen shot:
![image](https://cloud.githubusercontent.com/assets/4115566/14796735/da74987e-0afc-11e6-8cff-b7a24e146c31.png)

**Comment by Arcanemagus** [comment]
Those are all listed as Hack files, which aren't PHP files. This linter will only activate on _pure_ PHP, as that is all that it understands how to handle.

**Comment by yinanfang** [comment]
Oh, I see what's wrong here. The Atom automatically detect the file as Hack. However, this is just PHP files and there's `<?php` tag the the very beginning. Other than manually change the syntax settings to PHP, do you know if there's any way to correct the auto-detection?

**Comment by yinanfang** [comment]
I just found the solution here: [Atom file type setting](http://stackoverflow.com/questions/22363070/how-do-i-make-a-default-syntax-by-filetype-in-atom-text-editor/32508353#32508353)
