### ISSUE TITLE
Support project-specific PHP executable

### ISSUE THREAD

**Issue by mjanser** [AtomLinter/linter-php#169]
I work on multiple projects with different PHP versions and they all use vagrant for this and other reasons. Therefore it doesn't make sense to use a local PHP installation. With the current implementation of this linter it doesn't seem to be possible to execute PHP inside the corresponding vagrant box.

I tried it with the following script saved in a file and configured as the PHP executable:
```bash
vagrant ssh -c "php $@"
```

But this script is probably not executed in the project's directory. Is it possible to do that? Or maybe set an environment variable containing the directory before executing the script?

**Comment by Arcanemagus** [comment]
Sure it's possible, should be as simple as figuring out the current directory and specifying the `cwd` option to `exec()`.

**Comment by nicolasmure** [comment]
Hello,

If you want to specify a version of PHP without changing this plugin, you can try the following :

make an executable .sh file as it 
```bash
#!/bin/bash

docker run -i -a STDOUT --rm php:7 php $@
```
and point to it into the plugin's config.
You should then be able to choose the PHP version from this file. I know this is not the best solution but I hope it could help. Actually, I came to this solution while trying to use the plugin without having to install PHP on my machine.

**Comment by mjanser** [comment]
I created a pull request #172 and tested with this script:

```bash
#!/bin/bash
 
if [ -f Vagrantfile ]; then
    vagrant ssh -c 'php $@ 2>&1'
else
    php $@
fi 
```

**Comment by dudheit** [comment]
Hi, can you give me some advice how to configure the PHP executable path for a vagrant box? I've tried ``vagrant ssh -c "$CMD"`` which does not work.
