### ISSUE TITLE
Windows 10 Unable to determine PHP version

### ISSUE THREAD

**Issue by XaBerr** [AtomLinter/linter-php#174]
I use windows 10.
I have set my path: "C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php5617x160315153318\php.exe" in environment variables.
I have set the same path in config input.
This is my "php -v":

```
PHP 5.6.17 (cli) (built: Jan  6 2016 13:28:38)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

```
But I get this error: "Unable to determine PHP version".
What am I doing wrong?

**Comment by Arcanemagus** [comment]
That should [definitely work](https://regex101.com/r/oZ8rW0/1).

If you open Developer Tools, place a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/lib/main.coffee#L16) and then reload Atom (<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>R</kbd>) what does `output` contain?

**Comment by XaBerr** [comment]
![immagine](https://cloud.githubusercontent.com/assets/16030020/16411790/2dd59122-3d29-11e6-96ab-415d28b3dc63.png)

The script throws an exception at line 16

**Comment by Arcanemagus** [comment]
It looks like you have the _folder_ and not the full path to `php.exe` entered into your `linter-php` settings, try correcting that to the full path of `php.exe`.

**Comment by XaBerr** [comment]
You're right, my fault!
Thank you.
