### ISSUE TITLE
Allow overriding error_reporting level

### ISSUE THREAD

**Issue by dtwist** [AtomLinter/linter-php#179]
I've had this linter installed for ages, but it has never worked for me (just shows "no errors" for all PHP files). Finally getting around to troubleshooting it, since I'm spending almost all my time in Atom now and am having to perform maintenance on some old PHP projects. :) 

I've read through all the past "not working" issues here, but have not found any obvious recourse for my case; hoping someone here can help. Some details that could help diagnose (let me know if I can provide anything else):

#### OS
```
Mac OS X Yosemite 10.10.5 (14F1808)
```

#### PHP Version (installed via homebrew)
```
PHP 5.6.23 (cli) (built: Jun 24 2016 21:08:27) 
```
I updated the path per instructions in linter's settings pane

#### Atom and package versions installed
```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

Remote-FTP@0.8.3
Sublime-Style-Column-Selection@1.5.1
atom-beautify@0.29.9
autobot-syntax-theme@0.3.0
autocomplete-html-entities@0.1.0
base16-dark-syntax@0.1.0
block-travel@1.0.4
chester-atom-syntax@0.1.1
codebug@1.0.0
color-picker@2.2.1
custom-title@1.0.1
dark-petroleum-syntax@0.1.3
docblockr@0.7.3
duotone-dark-earth-syntax@1.0.0
duotone-dark-forest-syntax@1.0.0
duotone-dark-sea-syntax@1.0.0
duotone-dark-space-muted-syntax@1.0.0
duotone-dark-space-syntax@1.0.0
duotone-dark-syntax@1.0.0
ekini-like@0.9.1
emmet@2.4.3
file-icons@1.7.16
fonts@1.5.0
glacier-syntax@0.0.4
highlight-line@0.11.1
highlight-selected@0.11.2
improved-chester-atom-syntax@0.2.0
kobalt@0.5.0
language-apache@1.5.0
language-spacebars@0.2.2
linter@1.11.14
linter-eslint@7.2.4
linter-php@1.2.0
meteor-api@2.20.0
meteor-helper@0.28.0
meteor-snippets@0.5.0
mukluk-syntax@0.4.0
my-atom-theme-syntax@0.0.0
newton-dark-syntax@1.1.5
nil-one-syntax@1.0.0
oceanic-next@0.1.2
oceanic-next-dark@0.0.8
open-recent@5.0.0
orchid@0.4.0
pane-move-plus@0.3.1
pane-split-moves-tab@0.1.0
peacock-syntax@1.4.0
php-debug@0.2.3
polaris-syntax@0.1.0
predawn-syntax@1.0.2
project-manager@2.9.7
react@0.15.0
revert-buffer@0.5.0
semantic-ui@1.0.7
smart-tab-name@1.0.5
sort-lines@0.14.0
spacegray-chalk-syntax@7.0.4
specials@1.0.0
subtle@0.1.0
symbols-tree-view@0.13.2
tab-smart-sort@0.1.4
template-generator@0.12.2
toggle-quotes@1.0.0
unity-ui@2.1.5
```

#### Atom Editor Scope of php files:
```
text.html.php
meta.embedded.block.php
source.php
```

#### Results of running `apm test` in the package's directory
```
[7307:0708/111628:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
[7311:0708/111628:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
[7307:0708/111629:INFO:CONSOLE(52)] "Window load time: 507ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (52)
..F[7307:0708/111629:INFO:CONSOLE(58)] "Uncaught (in promise) TypeError: Cannot read property 'type' of undefined", source: /Users/dtwist/.atom/packages/linter-php/spec/linter-php-spec.js (58)
F..[7307:0708/111630:INFO:CONSOLE(96)] "Uncaught (in promise) TypeError: Cannot read property 'type' of undefined", source: /Users/dtwist/.atom/packages/linter-php/spec/linter-php-spec.js (96)
F

The php -l provider for Linter
  checks bad.php and
    it finds at least one message
      Expected 0 to equal 1.
        Error: Expected 0 to equal 1.
        at /Users/dtwist/.atom/packages/linter-php/spec/linter-php-spec.js:45:35
        at process._tickCallback (node.js:392:9)
    it verifies that message
      Expected promise to be resolved, but it was rejected with: Cannot read property 'type' of undefined {  }
  it handles fatal errors
    Expected promise to be resolved, but it was rejected with: Cannot read property 'type' of undefined {  }


Finished in 0.722 seconds
7 tests, 7 assertions, 3 failures, 0 skipped

Tests failed
```

**Comment by Arcanemagus** [comment]
Can you open Atom's developer tools, find this package's files and place a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/lib/main.coffee#L43) to see if the linter is even being called?

If you hit that breakpoint, place one [here](https://github.com/AtomLinter/linter-php/blob/v1.2.0/lib/main.coffee#L52) and report back the contents of `output`.

**Comment by dtwist** [comment]
Hi Landon,

Thanks for the quick reply! The linter is being called, output is:
```
"Errors parsing -"
```

And if I break in the lint function, before exec'ing the helper, here are the local vars:
```
command: "/usr/local/bin/php"
filePath: "/Users/dtwist/Desktop/foo.php"
parameters: Array[5]
0: "--syntax-check"
1: "--define"
2: "display_errors=On"
3: "--define"
4: "log_errors=Off"
length: 5
__proto__: Array[0]
text: "<?php foo(');↵"
```

I pieced together the cli equivalent and got the same output:
```
> /usr/local/bin/php --syntax-check --define display_errors=On --define log_errors=Off < /Users/dtwist/Desktop/foo.php
Errors parsing -
```

So, I looked at my php.ini and it turns out to be an issue with `error_reporting` (set to the default of "error_reporting = E_ALL & E_COMPILE_WARNING & E_COMPILE_ERROR
"). Updating the cli command to override that setting gets me:
```
/usr/local/bin/php --syntax-check --define display_errors=On --define log_errors=Off --define error_reporting=E_ALL < /Users/dtwist/Desktop/foo.php

Parse error: syntax error, unexpected '');' (T_ENCAPSED_AND_WHITESPACE) in - on line 1

Errors parsing -
```
And, subsequently updating the php.ini directly to just use E_ALL gets the linter working. huzzah!

Takeaway: perhaps it would be good to add an option to the linter's settings:
PHP error_reporting level:
(  ) E_ALL
(  ) as set in php.ini
(  ) other: ___________

Where choosing the first or third option adds the --define statement to the helper's parameters. I'd default to E_ALL to prevent this issue for new users, but set to the second option for upgrades, to avoid changing behavior for existing users.

**Comment by Arcanemagus** [comment]
Very interesting, that's not the default value in any of the `php.ini` I've seen, which list the following:

```ini
; error_reporting
;   Default Value: E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED
;   Development Value: E_ALL
;   Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
```

That's a good idea about overriding it, although since the only difference would be more messages of things that should probably be fixed, I'll probably set the default to `E_ALL` for everyone.

**Comment by dtwist** [comment]
@Arcanemagus Glad I was able to make a contribution. And very glad to have this package working in Atom. :)
