### ISSUE TITLE
Error re: ENOENT

### ISSUE THREAD

**Issue by FashaG** [AtomLinter/linter-php#203]
Background:
Windows 10
php -v
PHP 7.0.10 (cli) (built: Aug 18 2016 10:03:00) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

Path is set in php-linter to:
C:\Program Files\php

On any change in a .php file I get this error:

![atomerror](https://cloud.githubusercontent.com/assets/17938612/18297635/02db30d8-7480-11e6-94a3-40c6821d3748.PNG)

Any help would be appreciated.  Please be patient.
Thanks...
Chris
[edited to show correct screen shot]

**Comment by Arcanemagus** [comment]
Can you try putting the results of `where.exe php` into the Executable field?

For example on my system I would enter `C:\php5\php.exe` there.

**Comment by FashaG** [comment]
Landon:
You are a genius. That worked!
Thank you so much!
- Chris
