### ISSUE TITLE
Unknown operator '??' which was added in PHP7

### ISSUE THREAD

**Issue by gzklgg** [AtomLinter/linter-php#208]
While using the new operator ?? I get an error:
"Syntax error, unexpected '?' at line ..."
Take a look at the [link here](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

**Comment by Arcanemagus** [comment]
You should fix the path to PHP in your settings (or your `$PATH` environment variable), this package simply calls `php` with some options telling it to only check the syntax and not execute, so if you are seeing that then the `php` it is executing isn't PHP7.
