### ISSUE TITLE
OSX: "Make sure `php` is installed and on your PATH"

### ISSUE THREAD

**Issue by brentonstrine** [AtomLinter/linter-php#21]
I erratically get the following errors stacking up in the right side of my screen:

```
Failed to spawn command `php`. Make sure `php` is installed and on your PATH`
```
This happens even after a reboot. 

I looked at `/etc/paths` and it didn't look like `php` was in there, so I added it (`/usr/bin/php`) and rebooted. No effect.

**Comment by funsterisdafunniest** [comment]
@brentonstrine can you run the php inside a terminal on your mac directly? or you need to type in the full path?

**Comment by brentonstrine** [comment]
Sorry I don't understand what you mean when you say "run the php inside a terminal." I am using the Apache server to execute PHP on localhost, but the bug I'm reporting here is in the editor, not the browser, so there's no PHP being run at all, as far as I know.

**Comment by funsterisdafunniest** [comment]
i mean what would happen when you open the terminal on the osx and type 'php -v' (without the quote)

linter-php use php executable in order to lint the file. you need to have php installed on the machine you're using atom with.

**Comment by brentonstrine** [comment]
Ohhh, thanks for explaining. Yes, it's installed:

```
PHP 5.4.30 (cli) (built: Jul 29 2014 23:43:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

**Comment by funsterisdafunniest** [comment]
can you show me the output of these commands in the terminal?

<code>which php</code>


<code>echo $PATH</code>

**Comment by brentonstrine** [comment]
Thanks so much for your help. 

```
xxx$ which php
/usr/bin/php
xxx$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin/php:/opt/X11/bin:/usr/local/git/bin
```

**Comment by funsterisdafunniest** [comment]
hmm.. with that settings it should be possible to run linter without any problem.

what if you tried to use the settings like explained in the <a href="https://github.com/AtomLinter/linter-php">Main Page</a> under **Settings**  and change the null with /usr/bin/php

after that, you might need to restart atom

**Comment by Stanzilla** [comment]
Windows user here, my php is on my PATH variable

```
C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Users\Benjamin\AppData\Local\Atlassian\SourceTree\git_local\bin;C:\Users\Benjamin\AppData\Local\Atlassian\SourceTree\git_local\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\HashiCorp\Vagrant\bin;C:\ProgramData\ComposerSetup\bin;C:\Users\Benjamin\AppData\Roaming\Composer\vendor\bin;C:\xampp\php;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\TortoiseSVN\bin
```

Yet linter-php only works when I set the path to the executable again in the linter-php package options. Other packages like linter-lua work fine without me changing anything there. From what I found, linter-php seems to look at the USER PATH variable instead of the SYSTEM PATH variable, which is usually used.

Can this be changed?

**Comment by docterry** [comment]
Also a Windows user, and trying to get Atom working in a PortableApps format. Linter works fine if I give an absolute path to php.exe, such as "\Progs\AtomPortable\App\Atom\php\php.exe". However if I try a relative path such as "App\Atom\php\php.exe" it seems to find php.exe, but does not appear to perform the linting.

When I "cd \Progs\AtomPortable" and type "App\Atom\php\php.exe -v" it returns
```
PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

**Comment by steelbrain** [comment]
Please re-open another issue if it's still an issue after latest update

**Comment by venkatesh-oztek** [comment]
# **_

> `[ujuju## kikiki](

- 

- [ ] @ #1. url

)`

_**
