### ISSUE TITLE
exports._errnoException (util.js:890:11)

### ISSUE THREAD

**Issue by learning2** [AtomLinter/linter-php#211]
I am getting this error:

```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at C:\Users\Desktop\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:15:53
    at Object.<anonymous> (C:\Users\Desktop\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:14:18)
    at undefined.next (native)
    at step (C:\Users\Desktop\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:84:191)
    at C:\Users\Desktop\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:84:368
```

**Comment by Arcanemagus** [comment]
What version of Windows are you on? What does your setting for "Executable Path" look like?

**Comment by Arcanemagus** [comment]
Also what version of Atom are you on, as that stack trace doesn't look right for a current version.

**Comment by learning2** [comment]
I am using Windows 7 Ultimate  and it looks like 1.12.5 for Atom. I haven't been using Atom since this first attempt. I will look into learning Atom after I finish this project. Thank you for looking into this.

**Comment by Arcanemagus** [comment]
If you are still experiencing this error please ensure that either `php` is available on your `PATH` (ie: `where.exe php` gives a result), or enter the _full_ path of `php.exe` into the Executable Path setting.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still experiencing problems feel free to continue the discussion!
