### ISSUE TITLE
Can't find PHP

### ISSUE THREAD

**Issue by RustyAxeGames** [AtomLinter/linter-php#219]
Repeatedly reports can't find PHP type errors.

PHP Executable Path

c:\xampplite\php

That's where the executable lives, I'm on Windows 10.  Having PHP linting working properly would be great.

**Comment by Arcanemagus** [comment]
You need to set the _full_ path to PHP in the "PHP Executable Path" setting, eg:
![image](https://cloud.githubusercontent.com/assets/427137/19746831/fb402ed0-9b8c-11e6-8e32-2082e9365ddb.png)

This means I should put `C:\php5\php.exe` into that setting.

**Comment by RustyAxeGames** [comment]
I had tried that previous to using the double slashes but had not been methodical in trying all of the branches.  Anyhow, thanks to you, I now having functional PHP linting.  Thanks!

  "linter-php":
    executablePath: "c:\\xampplite\\php\\php.exe"

**Comment by Arcanemagus** [comment]
Just as an FYI: You should use the Settings interface inside Atom and avoid editing the `config.cson` directly if you can avoid it.

Glad you got it fixed though!
