### ISSUE TITLE
mysql can't be used on a modern web host

### ISSUE THREAD

**Issue by hawkon-open-source** [AtomLinter/linter-php#222]
mysql can't be used on a modern web host in PHP 7 the mysql have been change to mysqli

this is for all mysql commands like: mysql_fetch_array, mysql_query... and so on. And it's got new syntax

**Comment by Arcanemagus** [comment]
Checking for that has nothing to do with this package, this simply checks the _raw syntax_ of your code. As all of those are perfectly valid ways to call a function, it doesn't care that the function doesn't exist.

PHP's built in syntax checker is rather limited 😛.
