### ISSUE TITLE
Variable-length argument lists

### ISSUE THREAD

**Issue by lukasjuhas** [AtomLinter/linter-php#224]
Hey,

I'm getting parse error when using variable-length argument lists - I'm sure there is a way how to ignore these but mainly why are these considered as parse error? Is this just a bug or is there a reason behind this?

http://php.net/manual/ro/functions.arguments.php#functions.variable-arg-list

E.g.:

`$data = $api->{$method}()->{$call}(...$args);`

Thanks!

**Comment by Arcanemagus** [comment]
This linter is simply running `php -l` on your code, so if it's reporting an error then the code wouldn't run through `php` in the first place. Are you sure that the `php` available on your `$PATH` (or specified in the settings) is the version you are expecting?

**Comment by lukasjuhas** [comment]
Thanks for your reply @Arcanemagus, I'm gonna double check this on my work machine on Monday and let you know.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems let me know!
