### ISSUE TITLE
'php' could not be spawned (windows 10)

### ISSUE THREAD

**Issue by ubergeekzone** [AtomLinter/linter-php#227]
'php' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

php is added to my path, if i open cmd and do "php -v" it shows me the correct output.

PHP 5.6.24 (cli) (built: Aug  9 2016 12:59:00)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by Arcanemagus** [comment]
Can you try putting the results of running `where.exe php` into the Executable Path setting?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems feel free to continue the discussion!
