### ISSUE TITLE
"Unable to determine PHP version" error with hhvm

### ISSUE THREAD

**Issue by franksl** [AtomLinter/linter-php#231]
Hello,
I have hhvm installed on my Ubuntu 14.04 machine instead of php. When I open atom 1.13 or 1.12 I get an alert "Unable to determine PHP version".
This is the output of php -v:

```
HipHop VM 3.17.1 (rel)
Compiler: tags/HHVM-3.17.1-0-gdb3429c2130e5f7539bfd550c27a6bea9444b669
Repo schema: 68c9b831b56bea5d8c90f6fca5ea358cdaaea626
```

Path to php executable is the same as for php: /usr/bin/php and the linter works correctly after the alert.
Thanks,
Frank

**Comment by Arcanemagus** [comment]
I think I'm just going to remove this check, it was meant to help people get a working setup, but it seems to  cause more issues than it's worth.
