### ISSUE TITLE
Ability to lint on demand or increase timeout

### ISSUE THREAD

**Issue by johnbillion** [AtomLinter/linter-php#238]
The lint failure message appears if I pause even briefly while I'm typing PHP.

Is there a way to increase the timeout before linting is triggered? Or an option to lint only on demand?

**Comment by Arcanemagus** [comment]
You can increase the delay in the settings for the `Linter` package. That package also provides the option to completely disable on-the-fly linting (leaving just on-save). It also provides a command to manually trigger linting 😉.

**Comment by johnbillion** [comment]
Thanks!
