### ISSUE TITLE
[Linter] Error running PHP

### ISSUE THREAD

**Issue by Slepzs** [AtomLinter/linter-php#244]
[Linter] Error running PHP
See the console for more information?

How do i do that?, and what is the problem

**Comment by Slepzs** [comment]
FIXED

**Comment by IBaiBai** [comment]
Hello,how to solve this problem.

**Comment by fuyutsuki** [comment]
@Slepzs I get the same error, how did you solve it?

**Comment by fuyutsuki** [comment]
@Slepzs I'm sorry, I could fix it.

What to do if you encounter the same problem: Pass php's path from linter-php setting.
