### ISSUE TITLE
PHP Short Open Tag <?

### ISSUE THREAD

**Issue by richardbushell** [AtomLinter/linter-php#247]
Does linter-php not recognise the PHP SHORT OPEN TAG?  i.e.
Less-than-symbol plus ?
rather than
Less-than-symbol plus ?php
I think this is valid php, although discouraged, see:
http://php.net/manual/en/language.basic-syntax.phptags.php
We have a large library of .php files containing php short tags, but linter-php doesn't seem to recognise these as php unless we change every instance of these to ?php
Is there a flag or option to include or recognise these for php linting?

**Comment by Arcanemagus** [comment]
This linter simply runs `php --syntax-check --define display_errors=On --define log_errors=Off` on the file, so if your `php` is configured to enable them, then it should be working.

Is Atom not showing the files as PHP in the lower right?

**Comment by richardbushell** [comment]
Ah, I see, we had the PHP short-open-tag setting ON in our Wamp Server config settings, but this just Overrides the php.ini file setting for short_open_tag which was still set to Off in the php.ini file itself (referenced by linter-php). We changed this in the file too, and now it lints correctly with the Short Open Tag. Thanks.
