### ISSUE TITLE
linter php-l

### ISSUE THREAD

**Issue by satorstudio** [AtomLinter/linter-php#248]
it keeps going on and off

It's updated, the path is correct, php is properly instaleld on my Mac, but error check on the fly will only work sometimes.

I had to struggle a lot to get the linter packages to work on mac, and they did work fine until the last update today. And now no more

All i still have is the very annoying and not so useful php-md stylistic suggestions... but nothing if i forget a damn ; or a bracket :(

Please advise

**Comment by Arcanemagus** [comment]
> last update today

What update? [v1.3.2](https://github.com/AtomLinter/linter-php/releases/tag/v1.3.2) was released back on 2017-03-18. 😕

Are you getting any errors? Can you check the output of the `Linter: Debug` command to make sure this provider is active on the file you are expecting?

**Comment by satorstudio** [comment]
Thank you so much for coming back to me!
It was love at first sight with Atom but a troubled love so far!!! LOL

I installed Atom and the needed packages only one week ago or so

Today i was asked to update some of the linter packages; at present I have:
Atom 1.16 on Mac Os X 10.11 El Capitan
Linter 2.1.4
Linter-php 1.3.2
Linter-phpcs 1.6.2
Linter-phpmd 1.5.3
Linter-ui-defaults 1.2.4

Don't know where/how to run the Linter: debug command

**Comment by Arcanemagus** [comment]
To run the debug command go to Packages -> Command Palette -> Toggle (or likely <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and type "debug", it should be near the top of the list.

**Comment by fuyutsuki** [comment]
Perhaps I am in the same state so I will ask you a question here.
I used Win10 in the above method and obtained the following output.
![default](https://user-images.githubusercontent.com/16377174/29226416-f71df35a-7f0c-11e7-8da7-1eb7537ea8b2.JPG)
But it doesn`t work....

**Comment by Arcanemagus** [comment]
> Opened file is ignored: Yes

@fuyutsuki it looks like that file that you have open is ignored, likely in your VCS (eg. `git`).

**Comment by fuyutsuki** [comment]
@Arcanemagus It was invalidated by .gitignore.
Thank you for your reply.

**Comment by Arcanemagus** [comment]
Marking this issue as closed due to a lack of response. If you are still having issues setting this up @satorstudio feel free to comment further!
