### ISSUE TITLE
After recent updates, linter-php no longer works at all

### ISSUE THREAD

**Issue by lydianchord** [AtomLinter/linter-php#251]
I'm not sure if this was caused by the recent updates to Atom or the base linter packages, but I was able to use linter-php as recently as last week, and it no longer works at all while the other linters I use (linter-pyflakes, linter-jshint, etc.) still work. All of my linter packages are enabled, and `php -l` is still available on my command line.

EDIT: Actually it seems to be working again after I created a new file. I'm guessing this problem was caused by some weirdness in the base packages, so you probably ignore this issue?

**Comment by Arcanemagus** [comment]
Since nothing has changed here, sounds like it must have been some other package. Thanks for the update!
