### ISSUE TITLE
Error running PHP Error: spawn EACCES

### ISSUE THREAD

**Issue by broros** [AtomLinter/linter-php#253]
what is causing this?
this error still shows even after I delete linter-csslint.

```
/Users/brodyr/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running PHP Error: spawn EACCES
  at exports._errnoException (util.js:1026:11)
  at ChildProcess.spawn (internal/child_process.js:313:11)
  at exports.spawn (child_process.js:392:9)
  at /Users/brodyr/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:24:53
  at /Users/brodyr/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:23:18
  at undefined.next (<anonymous>:null:null)
  at step (/Users/brodyr/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:113:191)
  at /Users/brodyr/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:113:368
```

**Comment by Arcanemagus** [comment]
Usually this error is thrown when you have put a _directory_ in the configuration option for Executable Path, instead of the full path of `php`. You should be either leaving that as `php` to let the environment resolve it, or putting in the full path such as `/usr/local/bin/php`.

**Comment by broros** [comment]
does linter-php support php 7.1 ?

**Comment by Arcanemagus** [comment]
Yep, it's even one of the versions [specifically tested](https://github.com/AtomLinter/linter-php/blob/v1.3.2/.travis.yml#L11).

**Comment by broros** [comment]
actually it does not, if I switch to php 7.1.1  linter does not work, bottom right corner the language says HACK not PHP and no errors are thrown, as soon as I switch to php 5.6 every thing work again.

**Comment by Arcanemagus** [comment]
@broros That's the intended behavior. Hack isn't PHP, and `php` can't interpret it so it _shouldn't_ attempt to lint it. You'll need to either figure out how to get Nuclide to stop forcing PHP files to default to Hack files, or manually switch it each time.

**Comment by broros** [comment]
installed nuclide dependencies and seems to be working fine
