### ISSUE TITLE
Error out for any action

### ISSUE THREAD

**Issue by DonkihotD** [AtomLinter/linter-php#254]
![image](https://user-images.githubusercontent.com/17106272/27337066-0b12ec6e-55da-11e7-8ee4-21bc95477159.png)

This comes out for any action

**Comment by Arcanemagus** [comment]
Is `php` available in your `PATH`? If not, you may need to specify the _full_ path of `php` in the settings, eg `/usr/local/bin/php`.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having problems please address the above question/note.
