### ISSUE TITLE
[Linter] Error running PHP Error: Failed to spawn command `php`. Make sure `php` is installed and on your PATH

### ISSUE THREAD

**Issue by TrustedSamurai** [AtomLinter/linter-php#256]
Hello,

I've seen this error discussed before but don't understand from previous issues what the solution was.

When I check the path listed with this error message I find _helpers.js_, _index.js_ and _types.js_ but nothing that says php  (_C:\Users\janderson\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.js:102:24_)

I've checked Atom packages and see that I have _language-php_ installed. 

But I don't know what to try next?

Thank you,

John.

**Comment by Arcanemagus** [comment]
The message is talking about the system wide `%PATH%` environment variable that determines where executables should automatically be found.

Do you have [PHP](http://www.php.net/) installed on your system and have you modified your environment to make it available? You should be able to type `where.exe php` in a command prompt and get back a path.

**Comment by TrustedSamurai** [comment]
Hey Arcanemagus,
Thanks for writing.   when I execute a where.exe php from my Windows 10 Command Promt I get the message 
INFO: Could not find files for the given pattern(s).  

Is this supposed to search for an environment variable or something?  

Thanks.

**Comment by Isaactmh** [comment]
**This is very easy to fix.**

you need to edit the atom's config.cson file.
**It's locate in** C:\Users\YOURUSERNAME\.atom

**open with notepad and then add at the end of the file the section like the following:**

"linter-php":
  'executablePath': YOURPHPLOCATION **Example:** C:\php7.0\

Save, restart atom and will start to work. 
![atom](https://user-images.githubusercontent.com/10741394/27849896-a68a413e-611e-11e7-8b81-21a449b3b875.png)

**Comment by TrustedSamurai** [comment]
Hi Isaac,

 

Thank you for writing back directly. I thought it was a noob question but appreciate you taking the time.

 

I have located the config.cson file in c:\users\owners  its obviously the right file because as soon as I save it Atom (which is open) brings up an error saying Failed to Load.

 

The only php I could find was installed with Xamplite.  I was thiking that Atom would have its own reference or lookup.  Do you agree that I can use this?  I believe it only has php5+  but I can’t actually find where it is. I suspect I need to download/install php for Atom yes?

 

My config file currently looks like this.  

 

"*":

  core:

    disabledPackages: [

      "wordpress-api"

      "autocomplete-wordpress-hooks"

    ]

    telemetryConsent: "limited"

  editor:

    fontSize: 21

  "exception-reporting":

    userId: "b5d282c1-230f-4c96-a4b2-995bf34baf03"

  welcome:

    showOnStartup: false

linter-php":

'executablePath': C:\xampplite\ds-plugins\ds-cli\vendor\composer\composer\tests\Composer\Test\Autoload\Fixtures\php7.0\

 

 

Atom complains but that’s probably because it can’t fine php 7 at that location.  



 

 

Thanks again for your time.

**Comment by Isaactmh** [comment]
Hi TrustedSamurai.

If you are using Xampp the PHP executable it's on C:\xampp\php\

If you can see a blue PHP icon you are on the right folder. I don't know if the plug-in can work or not with PHP5 because I have the php7 I think so but you have to try.

In case you can't make it work, try to download the php7 standalone version and set the path in your config.cson. let me know what happen.

**Comment by Arcanemagus** [comment]
@Isaactmh and @TrustedSamurai: Unless you know _exactly_ what you are doing, you should always use the Settings within Atom to modify that file, it's easy to break things if you don't follow exactly how that file is supposed to work.

@TrustedSamurai within the settings it sounds like you just need to set the "Executable Path" option to `C:\xampp\php\php.exe`.

> I don't know if the plug-in can work or not with PHP5

@Isaactmh the package definitely works with PHP 5 😉.

**Comment by TrustedSamurai** [comment]
Ok, sounds straight forward.  :)

 

I open the environment variables window and add a new path to the PATH variable.  I can see PHP.EXE sitting at ‘C:\xamplite\php\php.exe’  so I add this to PATH.  Restart Atom and the following message appears.

 

I also went to Atom > Settings > Packages > php-integrator-base and added the path to PHP as c:/xamplite/php

 

But still get this message.

**Comment by Arcanemagus** [comment]
@TrustedSamurai The `PATH` environment variable expects a directory, while the "Executable Path" setting expects a full path (confusing terminology, I know).

If your PHP is located at `C:\xamplite\php\php.exe` then you would need to do _one_ of the following:
* Add `C:\xamplite\php` to your `PATH` environment variable to make `php` available system wide
* Set "Executable Path" to `C:\xamplite\php\php.exe` to make just `linter-php` work

**Comment by TrustedSamurai** [comment]
Thank you,  adding the path of the php executable to the environment variable 'Path' worked.

**Comment by braday** [comment]
I have similar problem getting php works because am using wamp for local host. I also tried placing all the PHP version but it gave me this error msg
```
Failed to load config.cson
[stdin]:15:47: error: unexpected newline
  # php path. run 'which php' to find the path
```
Here is what I set for the php.
  `"linter-php":`
  `# php path. run 'which php' to find the path`
  `'executablePath': D:\wamp\bin\php\php7.1.9`

Appreciated for any advises, thanks

**Comment by Arcanemagus** [comment]
@braday Don't edit your `config.cson` directly unless you know _exactly_ what you are doing. Remove those lines and use the Settings view within Atom to change the value 😉.

_Note: If you were curious about the several different things wrong with what you attempted above go back into the file after setting it in the UI to see all the differences._

**Comment by braday** [comment]
@Arcanemagus , Thanks for your prompt reply. I wonder where should I change the value in the Setting view in Atom? There is core setting, editor, system ...etc.

**Comment by braday** [comment]
@Arcanemagus Thanks for prompt reply. After I change the path setting inside your package is still saying 

> Linter Error running PHP

I wonder is that something wrong rather than this package installation? 
Regards

**Comment by Arcanemagus** [comment]
I couldn't really say without seeing the rest of the error 😉.

**Comment by braday** [comment]
@Arcanemagus : It working now, thanks for the reply.

**Comment by LeoEspinoza12** [comment]
@Arcanemagus thank you...

**Comment by chaitu111** [comment]
``
![screenshot_4](https://user-images.githubusercontent.com/11836029/45669507-f1dd2000-bb3d-11e8-8f1f-cf7daba16553.png)

**Comment by kpasso1015** [comment]
@chaitu111 Thank you. It goes good working.
