### ISSUE TITLE
Error on comparison operators

### ISSUE THREAD

**Issue by AnTSaSk** [AtomLinter/linter-php#257]
Hello,

On my last project i had to change the order of an multidimensional array, so i used uasort (see the code below), but the problem is the linter told me ''syntax error, unexpected '>'" when i used <=> operator.
Is that possible to fix it ?
This operator come from PHP7.0 (http://php.net/manual/en/language.operators.comparison.php)

`uasort($fields, function($item1, $item2) {
  return $item1['priority'] <=> $item2['priority'];
});`

**Comment by Arcanemagus** [comment]
You need to make sure that the `php` that Atom is using is PHP 7, it sounds like the `php` it is grabbing is an older version. By default it will use whichever one is on your `$PATH`.

**Comment by AnTSaSk** [comment]
Oh !
Indeed i don't have PHP7 on my computer, i only installed it on my VM...
Thank you for this quick response & this help !
