### ISSUE TITLE
Linter-PHP does not work in ATOM 1.18.0

### ISSUE THREAD

**Issue by hg2000** [AtomLinter/linter-php#259]
After upgrading Atom to 1.18.0 x64 on Ubuntu linter-php stopped working.
I see the linter window but no errors in the code show up.

I deinstalled all community packages except:

linter 2.2.0
linter-php 1.3.2
linter-ui-default 1.6.3
busy-signal 1.4.3

The path to php is correct. When I running php -l on the console works.

**Comment by khairulpetrcech** [comment]
mine too..does it give this error?

[stdin]:31:30: error: invalid regular expression flags php
  'executablePath': C:/xampp/php/

**Comment by Arcanemagus** [comment]
@khairulpetrcech You need the _full_ path of `php.exe`, not the directory it is in.

@hg2000 Are you seeing any error messages? If it's running and just not getting any results it "wouldn't show", if it wasn't working you would be getting an error...

**Comment by hg2000** [comment]
@Arcanemagus no, there are no error messages

**Comment by hg2000** [comment]
I don't now why, I changed nothing since yesterday, but suddenly it works ?!!

Somtimes things just need some time...

sorry for bothering you and thank you for your quick reply.
