### ISSUE TITLE
Function is not defined or imported anywhere

### ISSUE THREAD

**Issue by lsalomon** [AtomLinter/linter-php#260]
Hi !

I'm using a function from another namespace from the current i'm writting my class in, and every occurence of it is underlined in red. the tooltip contains the following text : 
> Function is not defined or imported anywhere

And I have the `use function` in place for the function and the code is working :(

Is this a known bug ? can you help me ? It's really annoying :/

**Comment by Arcanemagus** [comment]
This provider is _just_ a wrapper around running `php -l` on your code, if it's giving you a message then PHP itself would be giving you the message if you hadn't disabled warnings in your `php.ini` (I'm assuming).

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
