### ISSUE TITLE
Can't specify the php path

### ISSUE THREAD

**Issue by MindfulPol** [AtomLinter/linter-php#269]
Im on Windows 10, have xampp installed that's why I didnt install php manually but when I try to specify the path to php in my config.cson file I get the following error: 
                         
Failed to load config.cson
[stdin]:18:23: error: unexpected \
  'executablePath': C:\xampp\php
                               ^

This is exactly what I added to config.cson : 
'linter-php':
  'executablePath': C:\xampp\php
And php.exe is on that dir so I don't know what can I do to fix this, neither was I able to find someone with the same issue

**Comment by Arcanemagus** [comment]
Please don't manually edit `config.cson` unless you know _exactly_ what you are doing. Delete those lines and set it through the Settings page in Atom 😉.

**Comment by MindfulPol** [comment]
Okay thank you now its working!!!
