### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by benweier** [AtomLinter/linter-php#270]
OS: macOS Sierra 10.12.6
Atom: 1.21.0-beta1
Linter-PHP: 1.5.0

Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom Beta.app/Contents/Resources/app/src/electron-shims.js:9:10)
Object.<anonymous> (/Users/me/.atom/packages/linter-php/lib/main.js:102:71)
Generator.next (null:null:null)
step (/Users/me/.atom/packages/linter-php/lib/main.js:7:273)
<unknown> (/Users/me/.atom/packages/linter-php/lib/main.js:7:443)
lint (/Users/me/.atom/packages/linter-php/lib/main.js:7:99)
```

**Comment by Arcanemagus** [comment]
Huh, I could have sworn I _just_ fixed this, it must have been a different provider though. Thanks for the report!

**Comment by benweier** [comment]
It seems you likely did _just_ fix it, I have since found out that this only occurs for pending files only.

Steps to reproduce:

1. Open Atom and create a new pending editor with ctrl/cmd+n
2. Paste some code and manually set language to PHP
3. Introduce a linting error
4. Bare witness to the deprecation warning in the status bar

Warning does not present itself:

1. Open an existing PHP file
2. Introduce a linting error
