### ISSUE TITLE
Again "Failed to spawn command"

### ISSUE THREAD

**Issue by stefnats** [AtomLinter/linter-php#272]
Running Atom 1.20.1 with linter-php 1.5.1 on macOS 10.12.6
PHP 5.5.38 is installed under `/usr/local/bin/php`

    ➜  ~ /usr/local/bin/php -version
    PHP 5.5.38 (cli) (built: Aug  8 2017 09:30:38)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

config.cson:

    "linter-php":
     executablePath: "/usr/local/bin/php"

I get this error frequently since one of the last updates, i think it was an `linter-php` update.

    [Linter] Error running PHP Error: Failed to spawn command `/usr/local/bin/php`. Make sure `/usr/local/bin/php` is installed and on your PATH
        at /Users/justme/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:130:24
        at process._tickCallback (internal/process/next_tick.js:103:7)

I'm running out of ideas what this could cause. Any ideas?

**Comment by Arcanemagus** [comment]
How did you set the setting? Did you manually edit the file or did you use the Settings page?

Is `/usr/local/bin/php` executable for your user?

**Comment by stefnats** [comment]
I have set it before updating to `/usr/local/bin/php` using the Settings page and as you can see in my post i checked the version with my user using `/usr/local/bin/php -version`
Is there some log to debug further?

**Comment by stefnats** [comment]
Oddly enough, the error is now gone. Thanks for your help, i don't even know what caused this.
