### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by BigfootN** [AtomLinter/linter-php#273]
Hello,

I am having a problem with this package, it won't show any errors. Here are my settings:

    "linter-php":
        executablePath: "/usr/bin/php"

`php -l` works well. Here is the result of my `Linter: Debug` :

![Imgur](https://i.imgur.com/oUrxjyr.png)

Thank you very much in advance

**Comment by Arcanemagus** [comment]
![image](https://user-images.githubusercontent.com/427137/31648826-b1e14c38-b2c4-11e7-9b3a-2d5229504952.png)

It looks like you either didn't allow the installation of, or have disabled, `linter-ui-default`. So although `linter` is installed and likely reporting errors you have no interface to _display_ them. Please install/enable `linter-ui-default` to see the messages 😉.

**Comment by BigfootN** [comment]
Wow, I'm so stupid 😞 Thank you very much 😃 It now works 😄
