### ISSUE TITLE
Undefined Variables?

### ISSUE THREAD

**Issue by thomasfrobieter** [AtomLinter/linter-php#275]
This is more a question as an issue. Is there any further configuration possible? Syntax errors marked as errors correctly, but i got no warning for an undefined variable as i know it from phpStorm.

**Comment by Arcanemagus** [comment]
If you want anything other than syntax errors you will need an additional linter. This is _just_ the equivalent of running `php -l` on a file.

[linter-phpcs](https://atom.io/packages/linter-phpcs) provides [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) integration, and [linter-phpmd](https://atom.io/packages/linter-phpmd) provides integration of [PHPMD](https://phpmd.org/documentation/index.html).

**Comment by thomasfrobieter** [comment]
Thanks alot!

**Comment by Arcanemagus** [comment]
You may also be interested in [ide-php](https://atom.io/packages/ide-php), which requires [atom-ide-ui](https://atom.io/packages/atom-ide-ui) to expose a lot of it's features. The diagnostics can be shown with either `linter` or `atom-ide-ui`.

It looks like for lint checks it supports syntax checking (this package) as well as minimal docblock issues.
