### ISSUE TITLE
Syntax error on PHP 7's Null coalescing operator

### ISSUE THREAD

**Issue by pyodor** [AtomLinter/linter-php#276]
A null coalescing operator in php 7 emits a syntax error on the line.

**Comment by Arcanemagus** [comment]
It's likely your system has `php` as v5, you need to either fix it so the `php` in your `$PATH` is v7, or manually specify the path to `php` v7 in the settings.

**Comment by pyodor** [comment]
Yes indeed my system use PHP 5 and my code runs on a docker with PHP 7. Switching my system to PHP 7, the syntax error now gone. Thanks!
