### ISSUE TITLE
strict_types declaration in script with shebang

### ISSUE THREAD

**Issue by Arcesilas** [AtomLinter/linter-php#278]
Hi,

When a PHP script has a shebang, like that:

```php
#!/usr/bin/env php
<?php
declare(strict_types=1);
```

The linter raises an error `strict_types declaration must be the very first statement in the script`.

It seems the linter considers it's not, whereas it actually is. I don't know what statement the linter considers, in this case, as the first one, but the shebang must definitely be ignored.

**Comment by Arcanemagus** [comment]
This "linter" is just wrapping around calling `php -l` on your file, so PHP itself is what is giving you that message.

**Comment by Arcesilas** [comment]
When running `php -l` on that file I get: `No syntax errors detected in bin/generator`...

**Comment by Arcesilas** [comment]
Sorry, it seems I've made a mistake... It's another package that causes this error... Should have made some tests with other packages before opening this issue...
Really sorry for the inconvenience.

**Comment by Arcanemagus** [comment]
`steelbrain/linter` is only a manager of providers, it would have to be a different provider you have installed. You can see a list of the active ones for a file by running `Linter: Debug` from the Command Palette in Atom.

**Comment by Arcesilas** [comment]
This command is not available in the command palette...
I'm currently updating Atom from 1.21 to 1.22.

Anyway, I've deactivated all linter providers (even not related to PHP) and when only Linter and linter and linter-ui-default are active, the error is raised...

Thanks for your reply!

**Comment by Arcesilas** [comment]
I'm sorry again... Here's what I've done:
- disabled all linters
- enabled linter and linter-ui-default

Test: ok, no error.

Then:
- keep linters off
- keep linter and linter-ui-default active
- activate linter-php

Test: error is raised.

**Comment by Arcesilas** [comment]
The error seems random... I don't understand...
Done the same test again and the error is raised event when linter-php is deactivated.
Weird.

**Comment by Arcanemagus** [comment]
It looks like this is a known issue with `php`: https://bugs.php.net/bug.php?id=74339

**Comment by Arcesilas** [comment]
What is weird is that there is not error when actually running the script (as opposed to the behaviour described by OP of the PHP issue you mention), and there is no error when running `php -l`

Anyway, it seems that it's not a bug, it's a feature, so... And it just displays an error, which I can live with (harder, but still).

Thanks for your answers and your time!
And thanks for the package!

**Comment by Arcanemagus** [comment]
It _is_ quite bizarre how it keeps showing up and disappearing on you, but as any message _must_ be coming from `php` there isn't really anything that can be done here.
