### ISSUE TITLE
Spaceship operator as parse error

### ISSUE THREAD

**Issue by jimmyadaro** [AtomLinter/linter-php#280]
With PHP 7 this code for sort multi-dimensional arrays is totally valid:

```
usort($MyArray, function($a, $b) {
  return $a['value'] <=> $b['value'];
});
```

But in Atom I get "parse error", which I guess it is from the "spaceship operator" (<=>).

![linter-php error](https://user-images.githubusercontent.com/20187699/35576368-8edcb988-05bd-11e8-97d4-5cf2a137485e.png)

**Comment by Arcanemagus** [comment]
It's likely that the `php` being used in Atom is an older version. You may need to set the path to `php` v7 in the settings.

**Comment by jimmyadaro** [comment]
You are right! I set the path to XAMPP PHP file (`/Applications/XAMPP/xamppfiles/bin/php-7.1.6` for those who are interested) and is not throwing error anymore. Thank you.
