### ISSUE TITLE
shows only the first error

### ISSUE THREAD

**Issue by Fischmuetze** [AtomLinter/linter-php#282]
linter-php shows only the first php error per file on the linter pane and count also only one error per file on the status bar

atom 1.24.0
linter 2.2.0
linter-php 1.51

**Comment by Arcanemagus** [comment]
`php -l` itself only reports the first error it finds before exiting. It is only a basic syntax check built into the `php` interpreter.

I would highly recommend combining `linter-php` (syntax), `linter-phpmd` (semantic), and `linter-phpcs` (style) if you are working on PHP code.
