### ISSUE TITLE
syntax error, unexpected T_DOUBLE_ARROW, expecting T_DOUBLE_COLON

### ISSUE THREAD

**Issue by kaleidoc0de** [AtomLinter/linter-php#295]
Hi,
I'm using atom 1.28.2 with nuclide 0.323.0

I have installed this plugin as it works with nuclide's linter.
I have also installed the HipHop VM 3.21.0 php handler.

when attempting to use a list function to destruct an associative array like so:

`$aarr = array("foo" => $foo, "bar" => $bar);
list("foo" => $foo, "bar" => $bar) = $aarr;`

I get the error message
syntax error, unexpected T_DOUBLE_ARROW, expecting T_DOUBLE_COLON
when I expect no error messages.

is there any reason why it would suggest invalid syntax over valid syntax.
am I doing something wrong?

**Comment by Arcanemagus** [comment]
The messages come from running `php -l` on the code, so my _guess_ is that the version of `php` it is using doesn't understand that syntax. You can force it to use a specific version of `php` by setting a path in the settings.

**Comment by Brodito** [comment]
I have the same problem using the following code:

'cust_message' => 
   array (
    'en' => 'Hello',
    'es’ => ‘Hola',
    ),

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
