### ISSUE TITLE
Problem: PHP in Path

### ISSUE THREAD

**Issue by theking2** [AtomLinter/linter-php#299]
I use WampServer. WampServer diliberately discourages users to have PHP in path. Probably for the reason that it manages which php to use. Linter demands PHP to be in path.

FR: Allow administration of linter-php to specify the path to PHP without relying on the environment variable.

**Comment by Arcanemagus** [comment]
That's not an error message that would come from `linter-php`, so it must be a different community package that you have installed that is giving you that message.

Does it stop showing up if you disable `linter-php`?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
