### ISSUE TITLE
Problem: Linter-php does not work any more

### ISSUE THREAD

**Issue by jokin1999** [AtomLinter/linter-php#302]
The problem is linter-php has not worked any more since yesterday I changed settings of linter.
But I changed the settings back, just as it was when linter-php worked well, but nothing happened.
No error pops out, just nothing happened.
I ensured that I really installed linter, linter-php, busy-signal, linter-ui-default and they are all the newest one.
Linter debug info shows:
```
Platform: win32
Atom Version: 1.34.0
Linter Version: 2.3.0
Opened file is ignored: No
Matching Linter Providers: 
Disabled Linter Providers: 
Standard Linter Providers: 
Indie Linter Providers: 
UI Providers: 
  - Linter
  - minimap-linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - text.html.php
  - meta.embedded.block.php
  - source.php
  - meta.function-call.php
  - punctuation.definition.arguments.end.bracket.round.php
```
By the way, I tried use terminal to lint (`php -l filename.php`), it works.
What can I do to solve this problem?

**Comment by Arcanemagus** [comment]
Yeah, it looks like @steelbrain decided to drop v1 support in `linter` with no warning, and not as a major release like semver requires 🤦‍♂️.

This provider needs to be update to the v2 API before it will work with `linter@2.3.0`, till that gets done the only workaround is to downgrade to the previous version of `linter` with `apm install linter@2.2.0`.

**Comment by E-Haci** [comment]
i have also solved it with simple downgrade. Hope they will fix it ASAP.

apm delete linter
apm install linter@2.2.0

**Comment by jokin1999** [comment]
Thx :)
