### ISSUE TITLE
PHP Syntax Check: Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW)

### ISSUE THREAD

**Issue by Brodito** [AtomLinter/linter-php#305]
PHP Syntax Check: Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in your code on line 1

The code I am using is simple:

'cust_message' => 
   array (
    'en' => 'Hello',
    'es’ => ‘Hola',
    ),

Any suggestions ?

**Comment by Arcanemagus** [comment]
Messages come from `php`, not directly from here. _Usually_ this is due to the incorrect version of PHP being used to attempt to compile the code, you can force a specific path to PHP in the settings if you don't want to change the `$PATH` environment to point to the one you are expecting.
