### ISSUE TITLE
No Error information being shown

### ISSUE THREAD

**Issue by ninnypants** [AtomLinter/linter-php#38]
When linting a file no error information is being shown currently it just shows an empty line after the php icon.

![screen shot 2015-06-05 at 9 47 44 am](https://cloud.githubusercontent.com/assets/408862/8009728/0a9fd832-0b68-11e5-9b9a-348b53e9e56f.png)
![screen shot 2015-06-05 at 9 47 51 am](https://cloud.githubusercontent.com/assets/408862/8009730/0dbdc22c-0b68-11e5-817e-33eedc1e07cf.png)

Linter: 0.12.16
Linter-php: 0.0.15
Atom: 0.205.0
OS: OSX Yosemite
php version: 5.5.20

Settings:
```cson
  linter:
    statusBar: "Show error of the selected line"
    showHighlighting: false
    showErrorInline: false
    showInfoMessages: true
    lintDebug: true
  "linter-php":
    phpExecutablePath: "/usr/bin/php"
```

**Comment by steelbrain** [comment]
That's probably a parser error. and Yeah it's a bug.

**Comment by steelbrain** [comment]
Fixed by latest rewrite.
