### ISSUE TITLE
How to use???

### ISSUE THREAD

**Issue by kupoback** [AtomLinter/linter-php#39]
I'm trying to use this, however I'm unable to understand the installation process at all.

I have downloaded and installed PHP using IIS on Windows 8.1

Then...what? What am I pointing my config to? Where?

**Comment by Arcanemagus** [comment]
You need to set the "PHP Executable Path" option to the location of the php.exe on your system. Where that is depends entirely on where you installed it, the default location on Windows is usually `C:\php` or `C:\php5`.

**Comment by steelbrain** [comment]
Closing as the author didn't reply back with more info.
