### ISSUE TITLE
No heredoc recognition

### ISSUE THREAD

**Issue by Mychal713** [AtomLinter/linter-php#45]
![screenshot from 2015-07-11 14 29 30](https://cloud.githubusercontent.com/assets/2430977/8633739/9e14be92-27d9-11e5-8001-0ff6e30545a6.png)

Is there any way around this?

**Comment by Arcanemagus** [comment]
You need to remove the space at the end of line 37. Heredocs _must_ not have whitespace before the newline when you are starting it (and also no whitespace before or after on the ending line).
http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

Please close this as this isn't an issue with linter-php :wink:.

**Comment by steelbrain** [comment]
Closing, see comment above
