### ISSUE TITLE
Missing type field on Linter Response, Got: type,text,filePath,range

### ISSUE THREAD

**Issue by ChristianGrech** [AtomLinter/linter-php#51]
Getting the following issue quite often.

Error: Missing type field on Linter Response, Got: type,text,filePath,range
  at Object.module.exports.validateMessages (C:\Users\Christian\.atom\packages\linter\lib\helpers.coffee:20:19)
  at C:\Users\Christian\.atom\packages\linter\lib\messages.coffee:18:17
  at Emitter.module.exports.Emitter.emit (C:\Users\Christian\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\Christian\.atom\packages\linter\lib\editor-linter.coffee:76:22
  at process._tickCallback (node.js:367:9)

**Comment by steelbrain** [comment]
Can you provide a minimal repro example please?

**Comment by ChristianGrech** [comment]
It happens when I copy and paste a method and when writing a method which have the first letters the same. Ex:

```php
public function update() 
{
}

public function updateAll()
{
}
```

**Comment by steelbrain** [comment]
Gonna try to repro as soon as I'm on a computer

**Comment by ChristopheBoucaut** [comment]
I have the same problem. If i write a class with two methods which have the same name (copy/past to change after), i have this error also.

I tried the exemple of @ChristianGrech , but i don't have the bug when i write two methods which have the first letters the same :/.

**Comment by steelbrain** [comment]
Interesting, Can you provide the `php -l` result of file when you see the error and when you don't? Maybe it's a problem with our extraction regex.

**Comment by ChristianGrech** [comment]
@ChristopheBoucaut  Have you tried writing the second method (updateAll) as the error occurs during writing not once finished. When you write `public function update` the error will popup.

**Comment by ChristopheBoucaut** [comment]
With error popup (twice `update` method in the same class), php -l provides: 

    PHP Fatal error:  Cannot redeclare toto\Toto::update() in test.php on line 12
    Errors parsing test.php

With two names differents (update and updateAll), php -l provides:

    No syntax errors detected in test.php

**Comment by ChristopheBoucaut** [comment]
Complete code to test:

```php
<?php

namespace toto;

class Toto
{
    public function update()
    {

    }

    public function update()
    {

    }
}
```

**Comment by ChristopheBoucaut** [comment]
Thx @steelbrain <3
