### ISSUE TITLE
Linter-php not doing anything after fresh install

### ISSUE THREAD

**Issue by rvzanten** [AtomLinter/linter-php#55]
What is the problem:
Atom doesn't show me any errors when I create an error in my php script and then try to save it.

What i did:
1. Installed Atom
2. Installed linter-php via "apm install linter-php"
3. Didnt work, even with the php executable setting set to the correct value which is "/usr/bin/php"
I also tried the default value which is "php". This also didnt work, while "php" is in my path.
4. I deinstalled the package and reinstalled it. But still nothing is working.

Note: that between each step i restarted Atom and that i do have PHP installed.

**Comment by Arcanemagus** [comment]
Do you have other linters that work?
What operating system are you running?
Are you getting any errors in Atom?

**Comment by rvzanten** [comment]
-No, only tried the PHP linter.
-Xubuntu
-No, no errors.

**Comment by Arcanemagus** [comment]
Just to make sure: you do have the main [linter](https://github.com/atom-community/linter) package installed, right?

This will do nothing without it as all it does is provide a linter service for that to consume.

**Comment by rvzanten** [comment]
Thanks for that. 
I did not have the main Linter package installed.
RTFM

**Comment by nandordena** [comment]
Same error, with main linter installed.
- Windows 10
- php from Xamp
- path: C:/xampp/php/php.exe
- only tried the PHP linter.
- no console errors

--UPDATE--
I tried it now with linter-jscs and it worked fine ( just -jscs, -php continues broken )
