### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by pcruse3** [AtomLinter/linter-php#56]
I am using this with a PHP file and a I get this: `Error: Missing html/text field on Linter Response`

Here is my full log:

```Error: Missing html/text field on Linter Response at /Users/pcruse3/.atom/packages/linter/lib/validate.coffee:24:19 at Array.forEach (native) at Object.module.exports.Validate.messages (/Users/pcruse3/.atom/packages/linter/lib/validate.coffee:20:14) at MessageRegistry.set (/Users/pcruse3/.atom/packages/linter/lib/message-registry.coffee:22:18) at /Users/pcruse3/.atom/packages/linter/lib/linter-plus.coffee:27:17 at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11) at /Users/pcruse3/.atom/packages/linter/lib/linter-registry.coffee:57:32 at process._tickCallback (node.js:367:9)```

**Comment by steelbrain** [comment]
Thanks for the bug report, can you please provide a snippet that can reproduce this error? 
or does this error appear in all the files?

**Comment by pcruse3** [comment]
Seems like it happens anytime I use `$this`

```public function getCabin(){
        return $this->cabin;
    }```

**Comment by steelbrain** [comment]
I am unable to repro this on latest linter and latest linter-php :(
Please provide a solid way to repro and I'll re-open
