### ISSUE TITLE
Sometimes shows issues in markdown

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-php#65]
This package sometimes seems to show issues in markdown files which have nothing to do with PHP. (expect some PHP code snippets included e.g.)

![phplintererror](https://cloud.githubusercontent.com/assets/11966684/10118063/0dca4cb8-646e-11e5-846b-01890c7b7ae9.PNG)
file: https://gist.github.com/rugk/97067a051c3bbe74f116

Sometimes I have to save the markdown file multiple times or change some text (probably the text in the PHP code snippet), but at some point it works.

It seems this package is also checking md files...
I mean if it wants to do that I have nothing against it, but in this case it should just check the parts where PHP is actually used (the PHP snippets) and do not throw such 'false positives'.

**Comment by steelbrain** [comment]
That's an issue in `language-gfm` see https://github.com/atom/language-gfm/issues/121
