### ISSUE TITLE
Special characters must be escaped : [ < ].at line 1 col 1

### ISSUE THREAD

**Issue by BlaM** [AtomLinter/linter-php#77]
Not sure what happened but since the last update of [linter](https://github.com/AtomLinter/linter) today linter-php now tells me that I need to escape every "<" and ">" in my php files:

    <?PHP
    if ($x > 4) echo 'big!';
    ?>

This will throw three errors - one for each line of code.

It also tells me that Doctype must be declared first - which is not really true for PHP files.

So my best guess is that it tries to parse the file as HTML file (Atom says "PHP" in the bottom right).

Fun fact: It still recognizes actual PHP errors, so if I break the code (e.g. add space in the middle of echo) it will still report that.

**Comment by BlaM** [comment]
The issues seems not to be an linter-php problem. I also have [linter-htmlhint](https://atom.io/packages/linter-htmlhint) installed and that seems to raise the errors even though they appear in php code.

**Comment by Arcanemagus** [comment]
`linter-htmlhint` claims to `linter` that it knows how to handle code of the `text.html.php` scope, sounds like it might have issues with it in reality :stuck_out_tongue:.
