### ISSUE TITLE
linter-php doesn't find php.exe 

### ISSUE THREAD

**Issue by CutmastaD** [AtomLinter/linter-php#81]
When I open Atom.io, the linter-php doesn't seem to work, showing me all bunch of "not found blabla" dialog. I have to go to the settings of linter-php, delete the php.exe path from default path, close Atom.io, open it again and insert the path and then it works just fine.
But after some time it stops working and throws a bunch of dialog boxes.
Then I have to do the whole procedere again.

**Comment by Arcanemagus** [comment]
Since you are adding a `.exe` to PHP I'm assuming you're on Windows, for some reason Windows doesn't seem to grab the path from the environment properly and needs it fully specified. Since you say it works for a while and then suddenly breaks again my guess would be that your path to PHP is version specific and when you update it breaks?

Also when updating that setting you shouldn't need to restart Atom for it to take effect.

**Comment by Arcanemagus** [comment]
@CutmastaD Any updates?

**Comment by CutmastaD** [comment]
Yes, I use Atom on Windows. I don't know what you mean by updating. And I really need to close Atom for the linter to work, after I name the path, just checked it.
It just stops working after a while and throws a bunch of "Not found" messages.

**Comment by Arcanemagus** [comment]
I mean does it stop working when you update your PHP installation.

**Comment by CutmastaD** [comment]
I didn't update my PHP installation

**Comment by Arcanemagus** [comment]
So what you are saying is that it will be working, and then with no changes at all to your system it will suddenly stop working, causing you to need to reset the path?

Can you be a bit more specific than "not found"? Do you get a stack trace?

**Comment by CutmastaD** [comment]
Fortunately linter-php has been working the whole day now.
And yes, I didn't change any settings neither did I update anything.
I just coded and all of a sudden it threw the same messages, as if I didn't set any PHP path.

The next time it does that, I will take screenshots and report a new bug.
Thanks anyway

**Comment by CutmastaD** [comment]
Ok, the error occured again.
I also have jshint-package.
As soon, as I opened a .js file the jshint threw errors and the linter-php stopped working.

This message shows up, everytime, I change the PHP file but it's in german.

Error: "\\LINUX\vhosts\USER\vmolodew\kaffeekasse\public\js"
CMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.
UNC-Pfade werden nicht unterst�tzt.
Stattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.
  at exit (C:\Users\vmolodew\.atom\packages\linter-php\node_modules\atom-linter\lib\helpers.coffee:32:24)
  at triggerExitCallback (C:\Users\vmolodew\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\vmolodew\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)


With disabled jshint linter-php seems to have no problems anymore.

**Comment by Arcanemagus** [comment]
What version of Windows are you using?
Where is PHP installed, and what are you setting the path to in Atom?

----
For some reason you are getting output on `STDERR` that `CMD.EXE` doesn't support UNC paths... but neither of these plugins should be launching `CMD.EXE` in the first place so something bizarre is going on.

**Comment by Arcanemagus** [comment]
Any more information @CutmastaD? If you want a bit more interactive debugging you can reach me on  [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638).

**Comment by CutmastaD** [comment]
Oh sorry. I'm using win 7 professional Service Pack 1 64 Bit.
PHP is installed in "C:\php" and the executeable path I'm setting in Atom is "C:\php\php.exe".
As long as I don't use a other hinter, it works just fine.

**Comment by Arcanemagus** [comment]
Thought that I had already asked this, but apparently not:
What version of Atom are you using?
What is the output of `apm-list`?

**Comment by CutmastaD** [comment]
I use version 1.1.0.
And if you could tell me, how to get the output of apm list, that would be nice :)

**Comment by Arcanemagus** [comment]
Open Command Prompt or PowerShell and type that in, then copy the results here.

**Comment by CutmastaD** [comment]
Built-in Atom packages (90)
├── about@1.1.0
├── archive-view@0.61.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.9.2
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.22.0
├── autocomplete-snippets@1.7.1
├── autoflow@0.26.0
├── autosave@0.22.0
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.0.0
├── base16-tomorrow-light-theme@1.0.0
├── bookmarks@0.38.0
├── bracket-matcher@0.78.0
├── command-palette@0.36.0
├── deprecation-cop@0.54.0
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.185.0
├── fuzzy-finder@0.90.0
├── git-diff@0.56.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.55.0
├── incompatible-packages@0.25.0
├── keybinding-resolver@0.33.0
├── language-c@0.48.0
├── language-clojure@0.18.0
├── language-coffee-script@0.42.0
├── language-csharp@0.11.0
├── language-css@0.34.0
├── language-gfm@0.81.0
├── language-git@0.10.0
├── language-go@0.39.0
├── language-html@0.42.0
├── language-hyperlink@0.14.0
├── language-java@0.16.0
├── language-javascript@0.96.0
├── language-json@0.17.0
├── language-less@0.28.2
├── language-make@0.19.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.0
├── language-perl@0.30.0
├── language-php@0.30.0
├── language-property-list@0.8.0
├── language-python@0.40.0
├── language-ruby@0.60.0
├── language-ruby-on-rails@0.23.0
├── language-sass@0.42.0
├── language-shellscript@0.19.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.27.0
├── language-toml@0.16.0
├── language-xml@0.33.0
├── language-yaml@0.24.0
├── line-ending-selector@0.2.0
├── link@0.31.0
├── markdown-preview@0.154.0
├── metrics@0.53.0
├── notifications@0.59.0
├── one-dark-syntax@1.1.1
├── one-dark-ui@1.1.5
├── one-light-syntax@1.1.1
├── one-light-ui@1.1.5
├── open-on-github@0.38.0
├── package-generator@0.40.0
├── release-notes@0.53.0
├── settings-view@0.230.0
├── snippets@0.100.0
├── solarized-dark-syntax@0.38.1
├── solarized-light-syntax@0.22.1
├── spell-check@0.61.0
├── status-bar@0.79.0
├── styleguide@0.44.0
├── symbols-view@0.109.0
├── tabs@0.84.0
├── timecop@0.33.0
├── tree-view@0.190.0
├── update-package-dependencies@0.10.0
├── welcome@0.30.0
├── whitespace@0.31.0
└── wrap-guide@0.38.0

C:\Users\vmolodew\.atom\packages (18)
├── atom-alignment@0.12.1
├── atom-html-preview@0.1.13
├── atom-material-syntax@0.2.4
├── atom-material-ui@0.7.1
├── atom-storm-ui@2.0.1
├── autocomplete-php@0.3.7
├── color-picker@2.0.13
├── emmet@2.3.14
├── figlet@0.5.2
├── file-templates@0.1.1
├── imdone-atom@1.1.53
├── linter@1.10.0
├── linter-php@1.1.1
├── minimap@4.16.0
├── pigments@0.18.1
├── synced-sidebar@0.4.2
├── tool-bar@0.1.9
└── tool-bar-almighty@0.2.2


Is that right?

**Comment by Arcanemagus** [comment]
Are the files you are editing on a network share?

**Comment by CutmastaD** [comment]
Yes

**Comment by Arcanemagus** [comment]
I'm not sure anything can be done about that error then, as Node (within Atom) is what is launching PHP through CMD.EXE for some reason, which is causing that particular error.

The rest of the behaviour you are describing is.... bizarre, but I think also related to Atom. Neither of the two `linter-*` packages you have mentioned edit their (or any other) settings, so the settings changing on you would be an Atom bug if anything.

You don't happen to be using a roaming profile (or remapped folders with a default profile), would you?

I'm marking this as closed as I can't think of any way it would be possible for `linter-php` to have anything to do with this, but we can keep trying to diagnose the issues you are having.
