### ISSUE TITLE
Error : special characters must be escaped : [<] or [>]

### ISSUE THREAD

**Issue by eved42** [AtomLinter/linter-php#82]
Hi everyone,
since the last update, all my php files have this error every time I use theses characters "<" and ">".

Error on line 1 : `<?php`
or still on : `echo "<p>Hello !</p>";`

It is really annoying because I have a very high number of errors in my files and the linter is more binding than helpful... (example : a file with 340 lines have 141 issues...).

Before the last update, everything worked well.

Can you correct this please ? Thanks.

PS : I've created an issue on the linter github of atom community and they presumed this bug is in linter-php : https://github.com/atom-community/linter/issues/973#issuecomment-151456993

**Comment by Arcanemagus** [comment]
@eved42 I'm pretty sure this is actually an issue with `linter-htmlhint` (See https://github.com/AtomLinter/linter-htmlhint/issues/4), `linter-php` only runs `php -l` on the file, and it's impossible for it to give an error message like that as it only checks for PHP syntax errors.

**Comment by Arcanemagus** [comment]
It looks like nobody actually filed an issue on that over in the [HTMLHint](https://github.com/yaniswang/HTMLHint) repo, you might try that and see what they say.

**Comment by eved42** [comment]
Ok thank you for your answer. This morning, it seems to work again...

**Comment by cbp70** [comment]
ive seen this problem on few forums and theres a very simple way to get rid of it, open dreamweaver Go to Edit - preferences, in left panel highlight linting, then in edit rule set 

highlight html, click edit and apply changes, scroll down to where it says 
"spec-char-escape": true, and change it to false, edit your page click save and 

you will see no more errors

**Comment by shivalir12** [comment]
![image](https://user-images.githubusercontent.com/36067722/55771269-f864c200-5aa4-11e9-89d5-fd527a510a01.png)
Getting problem in including php file in html file. 
Error - Special char must be escaped out.

please help me out in solving this problem.

**Comment by Arcanemagus** [comment]
This is a bug in `htmlhint`, nothing to do with `linter-php`.

Please follow this issue for when it will be resolved: https://github.com/htmlhint/HTMLHint/issues/283

Until then unfortunately you'll simply have to ignore it.
