### ISSUE TITLE
Linter reports php spawn failure when source file disappears

### ISSUE THREAD

**Issue by VxJasonxV** [AtomLinter/linter-php#9]
I renamed a directory outside of Atom, and when I went back into Atom and changed tabs, I started receiving errors about `php` failing to spawn.

![screen shot 2015-01-31 at 23 31 15](https://cloud.githubusercontent.com/assets/1882/5991294/44fe316e-a9a1-11e4-9c7c-244e42c3ce39.png)

Opening a new instance of Atom to any other PHP file (in this case, the new directory that it was renamed to), the linter behaves correctly. I assume that the error code for the source file not being found is being interpreted somehow as an overall PHP interpreter failure.

The developer console ultimately reports the same thing as the pop-up dialog, but just in case the file/line number information is relevant:

![screen shot 2015-01-31 at 23 33 19](https://cloud.githubusercontent.com/assets/1882/5991298/959f8848-a9a1-11e4-9fef-4e93b42e8ada.png)

**Comment by steelbrain** [comment]
Please re-open another issue if it's still an issue after latest update
