### ISSUE TITLE
Prevents Live Reload in Dev Mode from Working

### ISSUE THREAD

**Issue by heisian** [AtomLinter/linter-php#93]
Problem:
When working with themes in dev mode, editing a theme file and saving it does not cause the window to update, reflecting the changes.

This only occurs when this plugin is enabled.

Reproduction:
1. Atom -> View -> Developer -> Open in Dev Mode...
2. Load a UI or Syntax theme
3. Begin editing that theme
4. Save a file - saved changes won't be propagated to the dev mode window.

**Comment by Arcanemagus** [comment]
This package has absolutely _nothing_ to do with any of that, so I'm a bit baffled as to how this is happening. Could you be a bit more specific on step 2 as I don't work on Atom themes? (Example file/project?)

**Comment by Arcanemagus** [comment]
For starters this package doesn't even activate unless you start editing a PHP file...

**Comment by heisian** [comment]
i thought it was weird as well.  I disabled all my community packages, then used process of elimination to find the one that was preventing me from getting a live update of the theme I was working on.  I have two other linters installed, a JS lint package and an HTML tidy package.

Not really sure how the two would be connected, either.

Step 2 means selecting a theme to use from the Themes panel, either Syntax or UI.

**Comment by heisian** [comment]
Here is a video demonstrating the bug:

https://www.youtube.com/watch?v=PRokokhnhWs

**Comment by heisian** [comment]
Here's a video demonstrating the bug:

https://www.youtube.com/watch?v=PRokokhnhWs

**Comment by Arcanemagus** [comment]
Seems to be working fine for me: https://youtu.be/YRR96U55478

Maybe try moving your `.atom` folder to a different location and trying a fresh profile?

**Comment by Arcanemagus** [comment]
Also open the Developer Tools and check for any errors.

**Comment by Arcanemagus** [comment]
Any further news @heisian?

**Comment by heisian** [comment]
hello, I just tried moving my .atom folder away and starting fresh.  After reinstalling all my previous packages and loading up my themes, I'm still running into the same problem.

**Comment by Arcanemagus** [comment]
I was actually able to reproduce this and have traced down what is somehow the issue: apparently _any_ package using `activationHooks` breaks this.

I'll be filing an issue over on https://github.com/atom/dev-live-reload about this as this isn't an issue with `linter-php`.

**Comment by heisian** [comment]
okay, seems like a good lead, thanks for helping with this!  I'll post over there as well when you open one up.
