### ISSUE TITLE
php.ini ignored

### ISSUE THREAD

**Issue by Lars-AP** [AtomLinter/linter-php#98]
lib/main.coffee appears to deliberately ignore the php.ini file:
Line:48        parameters.push('--no-php-ini')

I just had to comment this line out in order to resolve an issue where linter-php was returning an error in a php page where I was trying to output some xml:
<?xml version="1.0" encoding="UTF-8"?>

My php.ini has the settings:
short_open_tag = Off

This means that "<?" is not considered a PHP opening tag.

However the default value is "On" and as linter-php ignores php.ini, the "<?" in my XML above was causing the word "version" to be seen as PHP and therefore a syntax error.

Is there a reason the php.ini is explicitly ignored?  From my perspective, it would be ideal to have a configuration to enable it (or even specify a path for the php.ini to be used)?

**Comment by Arcanemagus** [comment]
When I took this over I simply left that as is, I honestly am not sure why it was setup like that, unless `--define` _doesn't_ override the php.ini?

**Comment by Arcanemagus** [comment]
Looks like it's been in there from the very beginning: [7b203716cc](https://github.com/AtomLinter/linter-php/blob/7b203716cc702482146a3079d852895e874e9b38/lib/linter-php.coffee#L11)

As it seems to work fine without it so far I'm submitting a PR to remove that line.

**Comment by Lars-AP** [comment]
Fast turnaround...  Thanks!!!
